In [1]:
import pandas as pd
import numpy as np
import requests
import os
import datetime as dt
import re
import ast

pd.set_option('display.max_columns', 999)

In [2]:
#Helper Functions

def convert_to_num(df):
    for col in df.columns:
        try:
            pd.to_numeric(df[col])
        except:
            print(f"Column {col} cannot be converted to numeric")
            continue

def labelDom(row):
    if row['DOM'] < 14:
        return True
    else:
        return False

def binaryDom(df):
    df['binaryDOM'] = df.apply(lambda row: labelDom(row), axis = 1)

def createDOM(df: pd.DataFrame, timestamp = False, convert = False):
    dom = df['soldDate'] - df['listDate']
    df['DOM'] = dom.astype("string")
    df.dropna(subset=['DOM'], inplace = True)
    df['DOM'] = df['DOM'].str.slice_replace(start=2)
    df['DOM'] = df['DOM'].astype("int")

def dfRemoveNA(df):
    df = df.replace('', np.nan)
    if sum(df.isna().sum()) != 0:
        df = df.dropna()
    return df

def dfFillNA(df, column):
    df = df.replace('', np.nan)
    df = df.fillna(value = {column: "No "+column})
    return df

def dfExtractFeatures(df: pd.DataFrame, key: str, columns: list):
    if type(df[key].values[0]) == str:
        serie = df[key].apply(lambda x: ast.literal_eval(str(x)))
        d = pd.DataFrame.from_dict(serie.tolist())
    elif type(df[key].values[0]) == dict:
        serie = pd.Series.to_dict(df[key])
        d = pd.DataFrame.from_dict(serie, orient='index')
    for i in range(len(columns)):
        df[columns[i]] = d[columns[i]]

    return df

def dfPriceDifference(df: pd.DataFrame):
    #should only be for clustering purposes only
    df['PriceDifference'] = df['soldPrice'] - df['listPrice']

def dfDatesRemoveTimeStamp(df: pd.DataFrame):
    df['listDate'] = df['listDate'].str.slice_replace(start = 10, repl="")
    df['soldDate'] = df['soldDate'].str.slice_replace(start = 10, repl="")

def dfConvertToDatetime(df: pd.DataFrame, timestamp = False):
    if type(df['listDate'].values[0]) == str:
        dfDatesRemoveTimeStamp(df)
    df['listDate'] = pd.to_datetime(df['listDate'])
    df['soldDate'] = pd.to_datetime(df['soldDate'])

def removeFeatures(df: pd.DataFrame, columns: list):
    #df = df.drop(['images', 'resource', 'timestamps','permissions','lastStatus','status','boardId','agents'], axis = 1)
    df = df.drop(columns, axis = 1)
    return df

#Data Augmentation

def countLevels(df: pd.DataFrame, column):
    series = df[column].value_counts()
    return series

def augmentCategorical(df, column, percent = 0.04):
    series = countLevels(df, column)
    total = np.sum(series.values)
    percentage = [x/total for x in series.values]
    
    for i in range(len(percentage)):
        if percentage[i] > percent:
            pass
        else:
            df = df.replace(to_replace = {column: series.index[i]}, value = 'Other '+column)

    return df

def augmentType(df, type, columns):
    for col in columns:
        df[col] = df[col].astype(df[col].astype(type))

    return df

def augmentNumericals(df):
    for i in range(len(df.columns)):
        if (type(df[df.columns[i]].values[0]) == str):
            numerical = re.search('^[-+]?[0-9]*\.?[0-9]+$', df[df.columns[i]].values[0])
            if numerical is not None:
                df[df.columns[i]] = df[df.columns[i]].astype(float)
    return df

def removeLowLevels(df, column):
    lst = []
    for i in range(len(df[column].value_counts().index)):
        if df[column].value_counts().values[i] < 11:
            lst.append(df[column].value_counts().index[i])

    for i in range(len(lst)):
        df = df[df[column] != lst[i]]
    return df

def removeOutliers(df):
    percentile90 = df['soldPrice'].quantile(0.90)
    percentile10 = df['soldPrice'].quantile(0.10)

    iqr = percentile90 - percentile10

    upper_limit = percentile90 + 3 * iqr
    lower_limit = percentile10 - 3 * iqr

    # df[df['soldPrice'] > upper_limit]
    # df[df['soldPrice'] < lower_limit]

    df = df[df['soldPrice'] < upper_limit]
    df = df[df['soldPrice'] > lower_limit]

    return df

In [3]:
raw_lease_df = pd.read_csv(os.getcwd()+"\\data\\raw_lease_data.csv")

In [4]:
raw_lease_df.columns

Index(['listDate', 'images', 'address', 'soldDate', 'resource', 'timestamps',
       'type', 'mlsNumber', 'permissions', 'soldPrice', 'details', 'class',
       'map', 'listPrice', 'lastStatus', 'status', 'boardId', 'agents'],
      dtype='object')

In [5]:
pd.unique(raw_lease_df['lastStatus'].values)

array(['Lsd', 'Exp', 'Sus', 'Ter', 'Lc', 'Sld'], dtype=object)

In [6]:
raw_lease_df.head()

,listDate,images,address,soldDate,resource,timestamps,type,mlsNumber,permissions,soldPrice,details,class,map,listPrice,lastStatus,status,boardId,agents
0,2019-04-16T00:00:00.000Z,"['IMG-N4418450_1.jpg', 'IMG-N4418450_2.jpg', '...","{'area': 'York', 'zip': 'L3Y0E1', 'country': N...",2019-05-06T00:00:00.000Z,Property:2381,{'listingUpdated': '2019-05-08T10:56:42.000Z'},Lease,N4418450,"{'displayAddressOnInternet': 'Y', 'displayPubl...",2200.0,"{'numBathrooms': '4', 'numBedrooms': '4', 'sqf...",ResidentialProperty,"{'latitude': '44.05193999999999', 'longitude':...",2100.0,Lsd,U,2,[]
1,2019-05-01T00:00:00.000Z,"['IMG-N4435010_1.jpg', 'IMG-N4435010_2.jpg', '...","{'area': 'York', 'zip': 'L4H1T3', 'country': N...",2019-05-06T00:00:00.000Z,Property:2381,{'listingUpdated': '2019-05-08T15:58:16.000Z'},Lease,N4435010,"{'displayAddressOnInternet': 'Y', 'displayPubl...",1350.0,"{'numBathrooms': '1', 'numBedrooms': '2', 'sqf...",ResidentialProperty,"{'latitude': '43.8168699', 'longitude': '-79.6...",1350.0,Lsd,U,2,[]
2,2019-05-03T00:00:00.000Z,"['IMG-N4437661_1.jpg', 'IMG-N4437661_2.jpg', '...","{'area': 'York', 'zip': 'L4E0T9', 'country': N...",2019-05-06T00:00:00.000Z,Property:2381,{'listingUpdated': '2019-05-07T11:06:02.000Z'},Lease,N4437661,"{'displayAddressOnInternet': 'Y', 'displayPubl...",3000.0,"{'numBathrooms': '4', 'numBedrooms': '5', 'sqf...",ResidentialProperty,"{'latitude': '43.9175319', 'longitude': '-79.4...",2999.0,Lsd,U,2,[]
3,2019-04-03T00:00:00.000Z,"['IMG-N4405561_1.jpg', 'IMG-N4405561_2.jpg', '...","{'area': 'York', 'zip': 'L9N 0T3', 'country': ...",2019-05-06T00:00:00.000Z,Property:2381,{'listingUpdated': '2019-05-08T14:23:19.000Z'},Lease,N4405561,"{'displayAddressOnInternet': 'Y', 'displayPubl...",2400.0,"{'numBathrooms': '4', 'numBedrooms': '4', 'sqf...",ResidentialProperty,"{'latitude': '44.09185', 'longitude': '-79.501...",2400.0,Lsd,U,2,[]
4,2019-04-24T00:00:00.000Z,['IMG-W4426017_1.jpg'],"{'area': 'Peel', 'zip': 'L4X4H2', 'country': N...",2019-05-06T00:00:00.000Z,Property:2381,{'listingUpdated': '2019-05-09T13:23:15.000Z'},Lease,W4426017,"{'displayAddressOnInternet': 'Y', 'displayPubl...",3400.0,"{'numBathrooms': '4', 'numBedrooms': '4', 'sqf...",ResidentialProperty,"{'latitude': '43.6064424', 'longitude': '-79.6...",3400.0,Lsd,U,2,[]

The datatypes are mainly objects, but there are dictionaries and floats/integers that are located inside each objects that may need to be converted. Certain predictors like number of bathrooms can be left as strings,

In [7]:
raw_lease_df.dtypes

listDate        object
images          object
address         object
soldDate        object
resource        object
timestamps      object
type            object
mlsNumber       object
permissions     object
soldPrice      float64
details         object
class           object
map             object
listPrice      float64
lastStatus      object
status          object
boardId          int64
agents          object
dtype: object

In [8]:
address = ['area', 'city', 'district', 'neighborhood']
details = ['numBathrooms','numBedrooms','sqft','style',]
map_ = ['latitude', 'longitude']
columns = ['listDate','soldDate','address','details','images', 'resource', 'timestamps','permissions','lastStatus','status','boardId','agents','type','mlsNumber','map']

lease_df = dfExtractFeatures(raw_lease_df, key = 'address', columns = address)
lease_df = dfExtractFeatures(lease_df, key = 'details', columns = details)
lease_df = dfExtractFeatures(lease_df, key = 'map', columns = map_)

In [9]:
lease_df.head()

,listDate,images,address,soldDate,resource,timestamps,type,mlsNumber,permissions,soldPrice,details,class,map,listPrice,lastStatus,status,boardId,agents,area,city,district,neighborhood,numBathrooms,numBedrooms,sqft,style,latitude,longitude
0,2019-04-16T00:00:00.000Z,"['IMG-N4418450_1.jpg', 'IMG-N4418450_2.jpg', '...","{'area': 'York', 'zip': 'L3Y0E1', 'country': N...",2019-05-06T00:00:00.000Z,Property:2381,{'listingUpdated': '2019-05-08T10:56:42.000Z'},Lease,N4418450,"{'displayAddressOnInternet': 'Y', 'displayPubl...",2200.0,"{'numBathrooms': '4', 'numBedrooms': '4', 'sqf...",ResidentialProperty,"{'latitude': '44.05193999999999', 'longitude':...",2100.0,Lsd,U,2,[],York,Newmarket,Newmarket,Glenway Estates,4,4,1500-2000,3-Storey,44.05193999999999,-79.49083999999999
1,2019-05-01T00:00:00.000Z,"['IMG-N4435010_1.jpg', 'IMG-N4435010_2.jpg', '...","{'area': 'York', 'zip': 'L4H1T3', 'country': N...",2019-05-06T00:00:00.000Z,Property:2381,{'listingUpdated': '2019-05-08T15:58:16.000Z'},Lease,N4435010,"{'displayAddressOnInternet': 'Y', 'displayPubl...",1350.0,"{'numBathrooms': '1', 'numBedrooms': '2', 'sqf...",ResidentialProperty,"{'latitude': '43.8168699', 'longitude': '-79.6...",1350.0,Lsd,U,2,[],York,Vaughan,Vaughan,Sonoma Heights,1,2,,2-Storey,43.8168699,-79.618265
2,2019-05-03T00:00:00.000Z,"['IMG-N4437661_1.jpg', 'IMG-N4437661_2.jpg', '...","{'area': 'York', 'zip': 'L4E0T9', 'country': N...",2019-05-06T00:00:00.000Z,Property:2381,{'listingUpdated': '2019-05-07T11:06:02.000Z'},Lease,N4437661,"{'displayAddressOnInternet': 'Y', 'displayPubl...",3000.0,"{'numBathrooms': '4', 'numBedrooms': '5', 'sqf...",ResidentialProperty,"{'latitude': '43.9175319', 'longitude': '-79.4...",2999.0,Lsd,U,2,[],York,Richmond Hill,Richmond Hill,Jefferson,4,5,3000-3500,2-Storey,43.9175319,-79.43661039999999
3,2019-04-03T00:00:00.000Z,"['IMG-N4405561_1.jpg', 'IMG-N4405561_2.jpg', '...","{'area': 'York', 'zip': 'L9N 0T3', 'country': ...",2019-05-06T00:00:00.000Z,Property:2381,{'listingUpdated': '2019-05-08T14:23:19.000Z'},Lease,N4405561,"{'displayAddressOnInternet': 'Y', 'displayPubl...",2400.0,"{'numBathrooms': '4', 'numBedrooms': '4', 'sqf...",ResidentialProperty,"{'latitude': '44.09185', 'longitude': '-79.501...",2400.0,Lsd,U,2,[],York,East Gwillimbury,East Gwillimbury,Holland Landing,4,4,3000-3500,2-Storey,44.09185,-79.50193
4,2019-04-24T00:00:00.000Z,['IMG-W4426017_1.jpg'],"{'area': 'Peel', 'zip': 'L4X4H2', 'country': N...",2019-05-06T00:00:00.000Z,Property:2381,{'listingUpdated': '2019-05-09T13:23:15.000Z'},Lease,W4426017,"{'displayAddressOnInternet': 'Y', 'displayPubl...",3400.0,"{'numBathrooms': '4', 'numBedrooms': '4', 'sqf...",ResidentialProperty,"{'latitude': '43.6064424', 'longitude': '-79.6...",3400.0,Lsd,U,2,[],Peel,Mississauga,Mississauga,Hurontario,4,4,,2-Storey,43.6064424,-79.6422499

In [10]:
lease_df.columns

Index(['listDate', 'images', 'address', 'soldDate', 'resource', 'timestamps',
       'type', 'mlsNumber', 'permissions', 'soldPrice', 'details', 'class',
       'map', 'listPrice', 'lastStatus', 'status', 'boardId', 'agents', 'area',
       'city', 'district', 'neighborhood', 'numBathrooms', 'numBedrooms',
       'sqft', 'style', 'latitude', 'longitude'],
      dtype='object')

Feature Engineering

In [11]:
pd.unique(lease_df['sqft'].values)

array(['1500-2000', '', '3000-3500', '2500-3000', '700-1100', '2000-2500',
       '3500-5000', '600-699', '1100-1500', '1200-1399', '500-599',
       '900-999', '800-899', '1400-1599', '700-799', '1000-1199',
       '1600-1799', '2000-2249', '0-499', '1800-1999', '< 700',
       '2250-2499', '5000+', '3500-3749', '500-699', '2750-2999',
       '3250-3499', '4000-4249', '2500-2749', '3000-3249', '1100-1299',
       '700-899', '3750-3999', '1300-1499', '900-1099', '4500-4749',
       '4750-4999', '4250-4499'], dtype=object)

In [12]:
lease_df.replace({"": np.nan}, inplace = True)
lease_df.replace({float("nan"): np.nan}, inplace = True)

In [13]:
dfConvertToDatetime(lease_df)

In [14]:
createDOM(lease_df)

In [15]:
lease_df['avg_sqft'] = [(int(value.split("-")[0])+int(value.split("-")[1]))/2 if not isinstance(value, float) and '-' in value else np.nan for value in lease_df['sqft']]

In [16]:
lease_df['avg_sqft']

0         1750.0
1            NaN
2         3250.0
3         3250.0
4            NaN
           ...
320766     949.5
320767       NaN
320768     549.5
320769     649.5
320770     749.5
Name: avg_sqft, Length: 320770, dtype: float64

In [17]:
lease_df['ppsqft'] = lease_df['listPrice']/lease_df['avg_sqft']

In [18]:
lease_df['ppsqft']

0         1.200000
1              NaN
2         0.922769
3         0.738462
4              NaN
            ...
320766    4.739336
320767         NaN
320768    4.549591
320769    4.926867
320770    3.202135
Name: ppsqft, Length: 320770, dtype: float64

In [19]:
pd.unique(lease_df['numBedrooms'].values)

array(['4', '2', '5', '3', '1', '0', '6', nan, '7', '8'], dtype=object)

In [20]:
lease_df['bathtobed_ratio'] = lease_df['numBathrooms'].astype("Int64")/lease_df['numBedrooms'].astype("Int64")

In [21]:
lease_df['latitude'] = lease_df['latitude'].astype("float")
lease_df['longitude'] = lease_df['longitude'].astype("float")

In [22]:
lease_df.tail()

,listDate,images,address,soldDate,resource,timestamps,type,mlsNumber,permissions,soldPrice,details,class,map,listPrice,lastStatus,status,boardId,agents,area,city,district,neighborhood,numBathrooms,numBedrooms,sqft,style,latitude,longitude,DOM,avg_sqft,ppsqft,bathtobed_ratio
320766,2023-03-14,"['IMG-W5965967_1.jpg', 'IMG-W5965967_2.jpg', '...","{'area': 'Toronto', 'zip': 'M6S 1A1', 'country...",2023-04-18,Property:2381,{'listingUpdated': '2023-04-19T21:21:01.000Z'},Lease,W5965967,"{'displayAddressOnInternet': 'Y', 'displayPubl...",4500.0,"{'numBathrooms': '3', 'numBedrooms': '3', 'sqf...",CondoProperty,"{'latitude': '43.6357626', 'longitude': '-79.4...",4500.0,Lsd,U,2,[],Toronto,Toronto,Toronto W01,High Park-Swansea,3,3,900-999,Apartment,43.635763,-79.467490,35,949.5,4.739336,1.0
320767,2023-03-23,"['IMG-W5985741_1.jpg', 'IMG-W5985741_2.jpg', '...","{'area': 'Toronto', 'zip': 'M6P2G3', 'country'...",2023-04-18,Property:2381,{'listingUpdated': '2023-04-19T17:01:48.000Z'},Lease,W5985741,"{'displayAddressOnInternet': 'Y', 'displayPubl...",3700.0,"{'numBathrooms': '1', 'numBedrooms': '2', 'sqf...",ResidentialProperty,"{'latitude': '43.6607634', 'longitude': '-79.4...",3550.0,Lsd,U,2,[],Toronto,Toronto,Toronto W02,High Park North,1,2,NaN,2-Storey,43.660763,-79.460102,26,NaN,NaN,0.5
320768,2023-03-20,"['IMG-C5975287_1.jpg', 'IMG-C5975287_2.jpg', '...","{'area': 'Toronto', 'zip': 'M2J1M5', 'country'...",2023-04-18,Property:2381,{'listingUpdated': '2023-04-19T22:13:37.000Z'},Lease,C5975287,"{'displayAddressOnInternet': 'Y', 'displayPubl...",2500.0,"{'numBathrooms': '1', 'numBedrooms': '1', 'sqf...",CondoProperty,"{'latitude': '43.7716467', 'longitude': '-79.3...",2500.0,Lsd,U,2,[],Toronto,Toronto,Toronto C15,Henry Farm,1,1,500-599,Apartment,43.771647,-79.344663,29,549.5,4.549591,1.0
320769,2023-04-13,"['IMG-C6024761_1.jpg', 'IMG-C6024761_2.jpg', '...","{'area': 'Toronto', 'zip': 'M5H0B1', 'country'...",2023-04-18,Property:2381,{'listingUpdated': '2023-04-19T22:49:33.000Z'},Lease,C6024761,"{'displayAddressOnInternet': 'Y', 'displayPubl...",3500.0,"{'numBathrooms': '1', 'numBedrooms': '1', 'sqf...",CondoProperty,"{'latitude': '43.6505301', 'longitude': '-79.3...",3200.0,Lsd,U,2,[],Toronto,Toronto,Toronto C01,Bay Street Corridor,1,1,600-699,Apartment,43.650530,-79.382148,5,649.5,4.926867,1.0
320770,2023-04-04,"['IMG-S6014669_1.jpg', 'IMG-S6014669_2.jpg', '...","{'area': 'Simcoe', 'zip': 'L4M 6H9', 'country'...",2023-04-18,Property:2381,{'listingUpdated': '2023-04-19T07:27:53.000Z'},Lease,S6014669,"{'displayAddressOnInternet': 'Y', 'displayPubl...",2400.0,"{'numBathrooms': '1', 'numBedrooms': '1', 'sqf...",CondoProperty,"{'latitude': '44.3896491', 'longitude': '-79.6...",2400.0,Lsd,U,2,[],Simcoe,Barrie,Barrie,North Shore,1,1,700-799,Apartment,44.389649,-79.684525,14,749.5,3.202135,1.0

In [23]:
44.389649	-79.684525

-35.294875999999995

In [24]:
top_left = [44.389649+0.05, -79.684525-0.05]
top_right = [44.389649+0.05, -79.684525+0.05]
bottom_right = [44.389649-0.05, -79.684525+0.05]
bottom_left = [44.389649-0.05, -79.684525-0.05]

coords = [[top_left, top_right, bottom_right, bottom_left, top_left]]

In [25]:
coords = [[top_left, top_right, bottom_right, bottom_left, top_left]]

In [26]:
coords

[[[44.439648999999996, -79.73452499999999],
  [44.439648999999996, -79.634525],
  [44.339649, -79.634525],
  [44.339649, -79.73452499999999],
  [44.439648999999996, -79.73452499999999]]]

In [27]:
coords = [[[-79.14121,43.79041],[-79.132627,43.773059],[-79.188932,43.886988],[-79.200605,43.877832],[-79.236654,43.869665],[-79.265836,43.860011],[-79.281972,43.856051],[-79.322828,43.84689],[-79.368146,43.839214],[-79.386021,43.836139],[-79.41486,43.838616],[-79.423787,43.836635],[-79.475285,43.82227],[-79.480092,43.813352],[-79.480778,43.803441],[-79.485585,43.79799],[-79.493825,43.794025],[-79.556996,43.779649],[-79.601628,43.761303],[-79.61611,43.758572],[-79.629934,43.750141],[-79.625471,43.728064],[-79.616888,43.713177],[-79.606245,43.695555],[-79.601095,43.685873],[-79.593885,43.681156],[-79.590109,43.672465],[-79.582212,43.671224],[-79.574659,43.670975],[-79.535177,43.58325],[-79.424627,43.619052],[-79.385488,43.602645],[-79.315451,43.612092],[-79.14121,43.79041]]]

In [28]:
def get_radius(lat, long, value = None):
    if value:
        return (lat + value, lat - value, long + value, long - value)
    else:
        return (lat + 0.005, lat - 0.005, long + 0.005, long - 0.005)
    
    #entire list[kings square:[[lat, long], [lat long], [] ,[]],[[], [], [] ,[]]]

def avg_radius(df):
    avg_prices = []
    for i in range(len(df)):
        avg_price = []
        radius = get_radius(df['latitude'].values[i], df['longitude'].values[i])
        for j in range(len(df)):
            if j != i:
                if (radius[0] <= df['latitude'].values[j] <= radius[1]) and (radius[2] <=  df['longitude'].values[j] <= radius[3]):
                    avg_price.append(df['listPrice'].values[j])
        if len(avg_price) == 0:
            avg_prices.append(np.nan)
        else:
            avg_prices.append(np.mean(avg_price))

    print(avg_prices)

    return avg_prices

def get_radius_(mlsNumber, api_key):
    url = f"https://api.repliers.io/listings/{mlsNumber}?similar?radius=1"

    payload = {}
    headers = {'repliers-api-key': api_key}
    r = requests.request("GET",url, params=payload, headers=headers)
    data = r.json()
    df = pd.DataFrame(data['listings'])
    return df

In [74]:
url = "https://api.repliers.io/listings/W5965967"
payload = {}
#payload = {'mlsNumber': "W5965967", 'status': 'U', 'lastStatus': 'Lsd',"resultsPerPage": 10000}
headers = {'repliers-api-key': os.environ['REPLIERS_KEY']}
r = requests.request("GET",url, params=payload, headers=headers)
print(r)
dat2 = r.json()

<Response [200]>

In [72]:
dat2

{'listDate': '2023-03-14T00:00:00.000Z',
 'rooms': {'1': {'features': 'Laminate',
   'level': 'Flat',
   'length': '6.10',
   'width': '3.25',
   'description': 'Living',
   'features3': 'W/O To Balcony',
   'features2': 'Combined W/Dining'},
  '2': {'features': 'Laminate',
   'level': 'Flat',
   'length': '6.10',
   'width': '3.25',
   'description': 'Dining',
   'features3': 'Combined W/Living',
   'features2': 'Open Concept'},
  '3': {'features': 'Open Concept',
   'level': 'Flat',
   'length': '6.10',
   'width': '3.25',
   'description': 'Kitchen',
   'features3': 'Quartz Counter',
   'features2': 'Stainless Steel Appl'},
  '4': {'features': 'Laminate',
   'level': 'Flat',
   'length': '3.05',
   'width': '3.05',
   'description': 'Prim Bdrm',
   'features3': '4 Pc Ensuite',
   'features2': 'His/Hers Closets'},
  '5': {'features': 'Laminate',
   'level': 'Flat',
   'length': '3.05',
   'width': '2.80',
   'description': '2nd Br',
   'features3': 'Large Window',
   'features2': 'Large Closet'},
  '6': {'features': 'Laminate',
   'level': 'Flat',
   'length': '3.05',
   'width': '2.95',
   'description': '3rd Br',
   'features3': 'Se View',
   'features2': 'North View'},
  '7': {'features': '',
   'level': '',
   'length': '',
   'width': '',
   'description': '',
   'features3': '',
   'features2': ''},
  '8': {'features': '',
   'level': '',
   'length': '',
   'width': '',
   'description': '',
   'features3': '',
   'features2': ''},
  '9': {'features': '',
   'level': '',
   'length': '',
   'width': '',
   'description': '',
   'features3': '',
   'features2': ''},
  '10': {'features': '',
   'level': '',
   'length': '',
   'width': '',
   'description': '',
   'features3': '',
   'features2': ''},
  '11': {'features': '',
   'level': '',
   'length': '',
   'width': '',
   'description': '',
   'features3': '',
   'features2': ''},
  '12': {'features': '',
   'level': '',
   'length': '',
   'width': '',
   'description': '',
   'features3': '',
   'features2': ''}},
 'originalPrice': '4500.00',
 'soldDate': '2023-04-18T00:00:00.000Z',
 'occupancy': 'Immediate',
 'timestamps': {'repliersUpdatedOn': '2023-04-20T01:30:40.000Z',
  'terminatedDate': None,
  'conditionalExpiryDate': None,
  'listingUpdated': '2023-04-19T21:21:01.000Z',
  'extensionEntryDate': None,
  'unavailableDate': '2023-04-18T00:00:00.000Z',
  'expiryDate': '2023-05-31T00:00:00.000Z',
  'listingEntryDate': '2023-03-14T00:00:00.000Z',
  'closedDate': '2023-05-01T00:00:00.000Z',
  'possessionDate': '2023-03-15T00:00:00.000Z',
  'idxUpdated': None,
  'photosUpdated': '2023-03-14T19:36:10.000Z',
  'suspendedDate': None},
 'condominium': {'pets': 'Restrict',
  'condoCorpNum': '2956',
  'parkingType': 'Owned',
  'fees': {'cableInlc': 'N',
   'waterIncl': 'N',
   'heatIncl': 'N',
   'taxesIncl': '',
   'parkingIncl': 'Y',
   'maintenance': '',
   'hydroIncl': 'N'},
  'stories': '35',
  'propertyMgr': 'Crossbridge Condominium Services Ltd.',
  'lockerLevel': '',
  'unitNumber': '02',
  'buildingInsurance': 'Y',
  'locker': 'None',
  'condoCorp': 'TSCC',
  'sharesPercentage': '',
  'ensuiteLaundry': '',
  'exposure': 'Ne',
  'lockerNumber': '',
  'lockerUnitNumber': '',
  'ammenities': ['Concierge',
   'Guest Suites',
   'Gym',
   'Indoor Pool',
   'Party/Meeting Room',
   'Visitor Parking']},
 'taxes': {'annualAmount': '', 'assessmentYear': ''},
 'office': {'brokerageName': 'SUTTON GROUP REALTY SYSTEMS INC., BROKERAGE'},
 'type': 'Lease',
 'nearby': {'ammenities': ['Clear View',
   'Hospital',
   'Lake/Pond',
   'Park',
   'Public Transit',
   '']},
 'lot': {'depth': None,
  'size': None,
  'width': None,
  'irregular': None,
  'acres': None,
  'legalDescription': None,
  'measurement': None},
 'mlsNumber': 'W5965967',
 'openHouse': {'1': {'date': '',
   'startTime': '',
   'endTime': '',
   'type': None,
   'status': None},
  '2': {'date': '',
   'startTime': '',
   'endTime': '',
   'type': None,
   'status': None},
  '3': {'date': '',
   'startTime': '',
   'endTime': '',
   'type': None,
   'status': None}},
 'permissions': {'displayAddressOnInternet': 'Y', 'displayPublic': 'N'},
 'soldPrice': '4500.00',
 'details': {'numKitchens': '1',
  'numParkingSpaces': '1.0',
  'laundryLevel': '',
  'zoningDescription': None,
  'moreInformationLink': None,
  'certificationLevel': '',
  'den': 'N',
  'yearBuilt': 'New',
  'balcony': 'Open',
  'alternateURLVideoLink': None,
  'exteriorConstruction1': 'Concrete',
  'elevator': '',
  'exteriorConstruction2': '',
  'roofMaterial': None,
  'zoning': '',
  'basement1': 'None',
  'basement2': '',
  'sqft': '900-999',
  'handicappedEquipped': '',
  'heating': 'Forced Air',
  'numRooms': '6',
  'landscapeFeatures': None,
  'virtualTourUrl': '',
  'landSewer': None,
  'energyCertification': '',
  'numBathrooms': '3',
  'greenPropertyInformationStatement': '',
  'liveStreamEventURL': None,
  'zoningType': None,
  'landAccessType': None,
  'businessSubType': None,
  'numKitchensPlus': '',
  'bathrooms': {'1': {'pieces': '4', 'level': 'Flat', 'count': '2'},
   '2': {'pieces': '2', 'level': 'Flat', 'count': '1'},
   '3': {'pieces': '', 'level': '', 'count': ''},
   '4': {'pieces': '', 'level': '', 'count': ''},
   '5': {'pieces': '', 'level': '', 'count': ''}},
  'swimmingPool': None,
  'constructionStyleSplitLevel': None,
  'leaseTerms': '1 Year',
  'numRoomsPlus': '',
  'flooringType': None,
  'farmType': None,
  'landDisposition': None,
  'viewType': None,
  'style': 'Apartment',
  'loadingType': None,
  'numGarageSpaces': '1.0',
  'parkCostMonthly': '',
  'airConditioning': 'Central Air',
  'familyRoom': 'N',
  'constructionStatus': None,
  'numBedrooms': '3',
  'description': 'Stunning, Brand New 995 Sq Ft Interior + 98 Sq Ft Balcony, 3 Bed, 2.5 Bath Unit At Luxury Mirabella Condos! Spectacular, Panoramic High Park, Skyline & Lake Views From 40th Floor! Open Style Living/Dining Space With Smooth 9 Ft Ceilings With Upgraded Lighting. Luxury Living On The Lake! Amazing Location With Easy Access To Downtown, 427, Lakeshore & Ttc. Steps From Lake And Lake Front Trails! Be The First To Live In This Amazing Unit!',
  'extras': 'Brand New S/S Samsung Appliances: Fridge, B/I Stove & Oven, Microwave And Range Hood Combo, Dishwasher, Stacked Washer/Dryer, All Elfs, 1 Parking. 10,000 Sq Ft Of Indoor Amenities (Excl. To East Tower), 18,000 Sq Ft Shared Outdoor Amenities',
  'livingAreaMeasurement': None,
  'patio': 'Open',
  'amperage': None,
  'centralAirConditioning': 'N',
  'furnished': 'N',
  'foundationType': None,
  'sewer': None,
  'propertyType': 'Condo Apt',
  'HOAFee': None,
  'commonElementsIncluded': 'Y',
  'numDrivewaySpaces': None,
  'numBathroomsPlus': None,
  'ceilingType': None,
  'waterSource': None,
  'numBedroomsPlus': '',
  'garage': 'Undergrnd',
  'centralVac': '',
  'sqftRange': None,
  'driveway': None,
  'numFireplaces': 'N',
  'energuideRating': None,
  'fireProtection': None,
  'storageType': None,
  'analyticsClick': None,
  'businessType': None,
  'numBathroomsHalf': None},
 'class': 'CondoProperty',
 'map': {'latitude': '43.6357626',
  'point': 'POINT (-79.4674903 43.6357626)',
  'longitude': '-79.4674903'},
 'images': ['IMG-W5965967_1.jpg',
  'IMG-W5965967_2.jpg',
  'IMG-W5965967_3.jpg',
  'IMG-W5965967_4.jpg',
  'IMG-W5965967_5.jpg',
  'IMG-W5965967_6.jpg',
  'IMG-W5965967_7.jpg',
  'IMG-W5965967_8.jpg',
  'IMG-W5965967_9.jpg',
  'IMG-W5965967_10.jpg',
  'IMG-W5965967_11.jpg',
  'IMG-W5965967_12.jpg',
  'IMG-W5965967_13.jpg',
  'IMG-W5965967_14.jpg',
  'IMG-W5965967_15.jpg',
  'IMG-W5965967_16.jpg',
  'IMG-W5965967_17.jpg',
  'IMG-W5965967_18.jpg',
  'IMG-W5965967_19.jpg',
  'IMG-W5965967_20.jpg',
  'IMG-W5965967_21.jpg',
  'IMG-W5965967_22.jpg',
  'IMG-W5965967_23.jpg',
  'IMG-W5965967_24.jpg',
  'IMG-W5965967_25.jpg',
  'IMG-W5965967_26.jpg',
  'IMG-W5965967_27.jpg',
  'IMG-W5965967_28.jpg',
  'IMG-W5965967_29.jpg',
  'IMG-W5965967_30.jpg',
  'IMG-W5965967_31.jpg',
  'IMG-W5965967_32.jpg',
  'IMG-W5965967_33.jpg'],
 'address': {'area': 'Toronto',
  'zip': 'M6S 1A1',
  'country': None,
  'city': 'Toronto',
  'streetNumber': '1926',
  'unitNumber': '4002',
  'streetDirection': 'W',
  'streetName': 'Lake Shore',
  'streetDirectionPrefix': None,
  'district': 'Toronto W01',
  'streetSuffix': 'Blvd',
  'neighborhood': 'High Park-Swansea',
  'state': 'Ontario',
  'majorIntersection': 'Lake Shore & Windermere',
  'communityCode': '01.W01.0450'},
 'comparables': [{'listDate': '2022-09-20T00:00:00.000Z',
   'images': ['IMG-W5769224_1.jpg',
    'IMG-W5769224_2.jpg',
    'IMG-W5769224_3.jpg',
    'IMG-W5769224_4.jpg',
    'IMG-W5769224_5.jpg',
    'IMG-W5769224_6.jpg',
    'IMG-W5769224_7.jpg',
    'IMG-W5769224_8.jpg',
    'IMG-W5769224_9.jpg',
    'IMG-W5769224_10.jpg',
    'IMG-W5769224_11.jpg',
    'IMG-W5769224_12.jpg',
    'IMG-W5769224_13.jpg'],
   'address': {'area': 'Toronto',
    'zip': 'M6S1A1',
    'country': None,
    'city': 'Toronto',
    'streetNumber': '1926',
    'unitNumber': '2610',
    'streetDirection': 'W',
    'streetName': 'Lake Shore',
    'district': 'Toronto W01',
    'streetSuffix': 'Blvd',
    'neighborhood': 'High Park-Swansea',
    'state': 'Ontario',
    'majorIntersection': 'Lake Shore/Windemere'},
   'soldDate': '2022-12-30T00:00:00.000Z',
   'timestamps': {'expiryDate': '2023-02-20T00:00:00.000Z',
    'terminatedDate': None,
    'listingEntryDate': '2022-09-20T00:00:00.000Z',
    'closedDate': '2023-01-15T00:00:00.000Z',
    'idxUpdated': None,
    'conditionalExpiryDate': None,
    'listingUpdated': '2023-01-03T10:17:53.000Z',
    'photosUpdated': '2022-10-11T14:03:01.000Z',
    'suspendedDate': None,
    'extensionEntryDate': '2022-11-03T11:50:38.000Z',
    'unavailableDate': '2022-12-30T00:00:00.000Z'},
   'condominium': {'parkingType': 'Owned',
    'fees': {'cableInlc': 'N',
     'waterIncl': 'N',
     'heatIncl': 'N',
     'taxesIncl': '',
     'parkingIncl': 'Y',
     'maintenance': '',
     'hydroIncl': 'N'},
    'ammenities': ['Bbqs Allowed',
     'Concierge',
     'Exercise Room',
     'Games Room',
     'Gym',
     'Visitor Parking'],
    'locker': 'Owned'},
   'office': {'brokerageName': 'TFN REALTY INC., BROKERAGE'},
   'type': 'Lease',
   'mlsNumber': 'W5769224',
   'soldPrice': '3900.00',
   'details': {'numParkingSpaces': '1.0',
    'numBathrooms': '2',
    'numBathroomsPlus': None,
    'numBedrooms': '3',
    'numBedroomsPlus': '',
    'propertyType': 'Condo Apt',
    'garage': 'Undergrnd',
    'sqft': '900-999',
    'numGarageSpaces': '1.0',
    'balcony': 'Open',
    'numBathroomsHalf': None},
   'listPrice': '3900.00',
   'lastStatus': 'Lsd'}],
 'resource': 'Property:2381',
 'raw': None,
 'updatedOn': '2023-04-19T21:21:01.000Z',
 'history': [],
 'daysOnMarket': '35',
 'agents': [],
 'coopCompensation': 'Half Month Rent + Hst',
 'listPrice': '4500.00',
 'lastStatus': 'Lsd',
 'status': 'U',
 'boardId': 2}

In [68]:
import json

print(lease_df['mlsNumber'].values[-4])

def get_avg_comparables(df):
    mlsNumbers = df['mlsNumber'].values[-5]
    avg_prices = []
    url = f"https://api.repliers.io/listings?mlsNumber=W5965967&mlsNumber=W5985741&status=U&lastStatus=Lsd"
    #url = f"https://api.repliers.io/listings/"
    payload = {}
    #payload = {'mlsNumber': "W5965967", 'status': 'U', 'lastStatus': 'Lsd',"resultsPerPage": 10000}
    headers = {'repliers-api-key': os.environ['REPLIERS_KEY']}
    r = requests.request("GET",url, params=payload, headers=headers)
    print(r)
    data = r.json()

    return data, r
    #data = json.loads(r.text)
    #     for value in data['comparables']:
    #         avg_price.append(float(value['listPrice']))

    #     if len(avg_price) == 0:
    #         avg_prices.append(np.nan)
    #     else:
    #         print(np.mean(avg_price))

    # return avg_prices

W5985741

In [69]:
data, r = get_avg_comparables(lease_df)

<Response [200]>

In [70]:
data

{'page': 1,
 'numPages': 1,
 'pageSize': 100,
 'count': 2,
 'statistics': {'listPrice': {'min': 3550, 'max': 4500}},
 'listings': [{'listDate': '2023-03-14T00:00:00.000Z',
   'rooms': {'1': {'features': 'Laminate',
     'level': 'Flat',
     'length': '6.10',
     'width': '3.25',
     'description': 'Living',
     'features3': 'W/O To Balcony',
     'features2': 'Combined W/Dining'},
    '2': {'features': 'Laminate',
     'level': 'Flat',
     'length': '6.10',
     'width': '3.25',
     'description': 'Dining',
     'features3': 'Combined W/Living',
     'features2': 'Open Concept'},
    '3': {'features': 'Open Concept',
     'level': 'Flat',
     'length': '6.10',
     'width': '3.25',
     'description': 'Kitchen',
     'features3': 'Quartz Counter',
     'features2': 'Stainless Steel Appl'},
    '4': {'features': 'Laminate',
     'level': 'Flat',
     'length': '3.05',
     'width': '3.05',
     'description': 'Prim Bdrm',
     'features3': '4 Pc Ensuite',
     'features2': 'His/Hers Closets'},
    '5': {'features': 'Laminate',
     'level': 'Flat',
     'length': '3.05',
     'width': '2.80',
     'description': '2nd Br',
     'features3': 'Large Window',
     'features2': 'Large Closet'},
    '6': {'features': 'Laminate',
     'level': 'Flat',
     'length': '3.05',
     'width': '2.95',
     'description': '3rd Br',
     'features3': 'Se View',
     'features2': 'North View'},
    '7': {'features': '',
     'level': '',
     'length': '',
     'width': '',
     'description': '',
     'features3': '',
     'features2': ''},
    '8': {'features': '',
     'level': '',
     'length': '',
     'width': '',
     'description': '',
     'features3': '',
     'features2': ''},
    '9': {'features': '',
     'level': '',
     'length': '',
     'width': '',
     'description': '',
     'features3': '',
     'features2': ''},
    '10': {'features': '',
     'level': '',
     'length': '',
     'width': '',
     'description': '',
     'features3': '',
     'features2': ''},
    '11': {'features': '',
     'level': '',
     'length': '',
     'width': '',
     'description': '',
     'features3': '',
     'features2': ''},
    '12': {'features': '',
     'level': '',
     'length': '',
     'width': '',
     'description': '',
     'features3': '',
     'features2': ''}},
   'originalPrice': '4500.00',
   'soldDate': '2023-04-18T00:00:00.000Z',
   'occupancy': 'Immediate',
   'timestamps': {'repliersUpdatedOn': '2023-04-20T01:30:40.000Z',
    'terminatedDate': None,
    'conditionalExpiryDate': None,
    'listingUpdated': '2023-04-19T21:21:01.000Z',
    'extensionEntryDate': None,
    'unavailableDate': '2023-04-18T00:00:00.000Z',
    'expiryDate': '2023-05-31T00:00:00.000Z',
    'listingEntryDate': '2023-03-14T00:00:00.000Z',
    'closedDate': '2023-05-01T00:00:00.000Z',
    'possessionDate': '2023-03-15T00:00:00.000Z',
    'idxUpdated': None,
    'photosUpdated': '2023-03-14T19:36:10.000Z',
    'suspendedDate': None},
   'condominium': {'pets': 'Restrict',
    'condoCorpNum': '2956',
    'parkingType': 'Owned',
    'fees': {'cableInlc': 'N',
     'waterIncl': 'N',
     'heatIncl': 'N',
     'taxesIncl': '',
     'parkingIncl': 'Y',
     'maintenance': '',
     'hydroIncl': 'N'},
    'stories': '35',
    'propertyMgr': 'Crossbridge Condominium Services Ltd.',
    'lockerLevel': '',
    'unitNumber': '02',
    'buildingInsurance': 'Y',
    'locker': 'None',
    'condoCorp': 'TSCC',
    'sharesPercentage': '',
    'ensuiteLaundry': '',
    'exposure': 'Ne',
    'lockerNumber': '',
    'lockerUnitNumber': '',
    'ammenities': ['Concierge',
     'Guest Suites',
     'Gym',
     'Indoor Pool',
     'Party/Meeting Room',
     'Visitor Parking']},
   'taxes': {'annualAmount': '', 'assessmentYear': ''},
   'office': {'brokerageName': 'SUTTON GROUP REALTY SYSTEMS INC., BROKERAGE'},
   'type': 'Lease',
   'nearby': {'ammenities': ['Clear View',
     'Hospital',
     'Lake/Pond',
     'Park',
     'Public Transit',
     '']},
   'lot': {'depth': None,
    'size': None,
    'width': None,
    'irregular': None,
    'acres': None,
    'legalDescription': None,
    'measurement': None},
   'mlsNumber': 'W5965967',
   'openHouse': {'1': {'date': '',
     'startTime': '',
     'endTime': '',
     'type': None,
     'status': None},
    '2': {'date': '',
     'startTime': '',
     'endTime': '',
     'type': None,
     'status': None},
    '3': {'date': '',
     'startTime': '',
     'endTime': '',
     'type': None,
     'status': None}},
   'permissions': {'displayAddressOnInternet': 'Y', 'displayPublic': 'N'},
   'soldPrice': '4500.00',
   'details': {'numKitchens': '1',
    'numParkingSpaces': '1.0',
    'laundryLevel': '',
    'zoningDescription': None,
    'moreInformationLink': None,
    'certificationLevel': '',
    'den': 'N',
    'yearBuilt': 'New',
    'balcony': 'Open',
    'alternateURLVideoLink': None,
    'exteriorConstruction1': 'Concrete',
    'elevator': '',
    'exteriorConstruction2': '',
    'roofMaterial': None,
    'zoning': '',
    'basement1': 'None',
    'basement2': '',
    'sqft': '900-999',
    'handicappedEquipped': '',
    'heating': 'Forced Air',
    'numRooms': '6',
    'landscapeFeatures': None,
    'virtualTourUrl': '',
    'landSewer': None,
    'energyCertification': '',
    'numBathrooms': '3',
    'greenPropertyInformationStatement': '',
    'liveStreamEventURL': None,
    'zoningType': None,
    'landAccessType': None,
    'businessSubType': None,
    'numKitchensPlus': '',
    'bathrooms': {'1': {'pieces': '4', 'level': 'Flat', 'count': '2'},
     '2': {'pieces': '2', 'level': 'Flat', 'count': '1'},
     '3': {'pieces': '', 'level': '', 'count': ''},
     '4': {'pieces': '', 'level': '', 'count': ''},
     '5': {'pieces': '', 'level': '', 'count': ''}},
    'swimmingPool': None,
    'constructionStyleSplitLevel': None,
    'leaseTerms': '1 Year',
    'numRoomsPlus': '',
    'flooringType': None,
    'farmType': None,
    'landDisposition': None,
    'viewType': None,
    'style': 'Apartment',
    'loadingType': None,
    'numGarageSpaces': '1.0',
    'parkCostMonthly': '',
    'airConditioning': 'Central Air',
    'familyRoom': 'N',
    'constructionStatus': None,
    'numBedrooms': '3',
    'description': 'Stunning, Brand New 995 Sq Ft Interior + 98 Sq Ft Balcony, 3 Bed, 2.5 Bath Unit At Luxury Mirabella Condos! Spectacular, Panoramic High Park, Skyline & Lake Views From 40th Floor! Open Style Living/Dining Space With Smooth 9 Ft Ceilings With Upgraded Lighting. Luxury Living On The Lake! Amazing Location With Easy Access To Downtown, 427, Lakeshore & Ttc. Steps From Lake And Lake Front Trails! Be The First To Live In This Amazing Unit!',
    'extras': 'Brand New S/S Samsung Appliances: Fridge, B/I Stove & Oven, Microwave And Range Hood Combo, Dishwasher, Stacked Washer/Dryer, All Elfs, 1 Parking. 10,000 Sq Ft Of Indoor Amenities (Excl. To East Tower), 18,000 Sq Ft Shared Outdoor Amenities',
    'livingAreaMeasurement': None,
    'patio': 'Open',
    'amperage': None,
    'centralAirConditioning': 'N',
    'furnished': 'N',
    'foundationType': None,
    'sewer': None,
    'propertyType': 'Condo Apt',
    'HOAFee': None,
    'commonElementsIncluded': 'Y',
    'numDrivewaySpaces': None,
    'numBathroomsPlus': None,
    'ceilingType': None,
    'waterSource': None,
    'numBedroomsPlus': '',
    'garage': 'Undergrnd',
    'centralVac': '',
    'sqftRange': None,
    'driveway': None,
    'numFireplaces': 'N',
    'energuideRating': None,
    'fireProtection': None,
    'storageType': None,
    'analyticsClick': None,
    'businessType': None,
    'numBathroomsHalf': None},
   'class': 'CondoProperty',
   'map': {'latitude': '43.6357626',
    'point': 'POINT (-79.4674903 43.6357626)',
    'longitude': '-79.4674903'},
   'images': ['IMG-W5965967_1.jpg',
    'IMG-W5965967_2.jpg',
    'IMG-W5965967_3.jpg',
    'IMG-W5965967_4.jpg',
    'IMG-W5965967_5.jpg',
    'IMG-W5965967_6.jpg',
    'IMG-W5965967_7.jpg',
    'IMG-W5965967_8.jpg',
    'IMG-W5965967_9.jpg',
    'IMG-W5965967_10.jpg',
    'IMG-W5965967_11.jpg',
    'IMG-W5965967_12.jpg',
    'IMG-W5965967_13.jpg',
    'IMG-W5965967_14.jpg',
    'IMG-W5965967_15.jpg',
    'IMG-W5965967_16.jpg',
    'IMG-W5965967_17.jpg',
    'IMG-W5965967_18.jpg',
    'IMG-W5965967_19.jpg',
    'IMG-W5965967_20.jpg',
    'IMG-W5965967_21.jpg',
    'IMG-W5965967_22.jpg',
    'IMG-W5965967_23.jpg',
    'IMG-W5965967_24.jpg',
    'IMG-W5965967_25.jpg',
    'IMG-W5965967_26.jpg',
    'IMG-W5965967_27.jpg',
    'IMG-W5965967_28.jpg',
    'IMG-W5965967_29.jpg',
    'IMG-W5965967_30.jpg',
    'IMG-W5965967_31.jpg',
    'IMG-W5965967_32.jpg',
    'IMG-W5965967_33.jpg'],
   'address': {'area': 'Toronto',
    'zip': 'M6S 1A1',
    'country': None,
    'city': 'Toronto',
    'streetNumber': '1926',
    'unitNumber': '4002',
    'streetDirection': 'W',
    'streetName': 'Lake Shore',
    'streetDirectionPrefix': None,
    'district': 'Toronto W01',
    'streetSuffix': 'Blvd',
    'neighborhood': 'High Park-Swansea',
    'state': 'Ontario',
    'majorIntersection': 'Lake Shore & Windermere',
    'communityCode': '01.W01.0450'},
   'resource': 'Property:2381',
   'raw': None,
   'updatedOn': '2023-04-19T21:21:01.000Z',
   'daysOnMarket': '35',
   'agents': [],
   'coopCompensation': 'Half Month Rent + Hst',
   'listPrice': '4500.00',
   'lastStatus': 'Lsd',
   'status': 'U',
   'boardId': 2},
  {'listDate': '2023-03-23T00:00:00.000Z',
   'rooms': {'1': {'features': 'Fireplace',
     'level': 'Flat',
     'length': '',
     'width': '',
     'description': 'Living',
     'features3': 'Hardwood Floor',
     'features2': 'Large Window'},
    '2': {'features': 'Combined W/Living',
     'level': 'Flat',
     'length': '',
     'width': '',
     'description': 'Dining',
     'features3': 'Hardwood Floor',
     'features2': 'W/O To Deck'},
    '3': {'features': 'Modern Kitchen',
     'level': 'Flat',
     'length': '',
     'width': '',
     'description': 'Kitchen',
     'features3': 'Slate Flooring',
     'features2': 'Marble Counter'},
    '4': {'features': 'Large Window',
     'level': 'Flat',
     'length': '',
     'width': '',
     'description': 'Den',
     'features3': 'Hardwood Floor',
     'features2': 'Closet'},
    '5': {'features': 'Window',
     'level': 'Flat',
     'length': '',
     'width': '',
     'description': 'Prim Bdrm',
     'features3': 'Hardwood Floor',
     'features2': 'Closet'},
    '6': {'features': 'Window',
     'level': 'Flat',
     'length': '',
     'width': '',
     'description': '2nd Br',
     'features3': 'Hardwood Floor',
     'features2': 'Closet'},
    '7': {'features': '4 Pc Bath',
     'level': 'Flat',
     'length': '',
     'width': '',
     'description': 'Bathroom',
     'features3': 'Slate Flooring',
     'features2': 'Soaker'},
    '8': {'features': '',
     'level': '',
     'length': '',
     'width': '',
     'description': '',
     'features3': '',
     'features2': ''},
    '9': {'features': '',
     'level': '',
     'length': '',
     'width': '',
     'description': '',
     'features3': '',
     'features2': ''},
    '10': {'features': '',
     'level': '',
     'length': '',
     'width': '',
     'description': '',
     'features3': '',
     'features2': ''},
    '11': {'features': '',
     'level': '',
     'length': '',
     'width': '',
     'description': '',
     'features3': '',
     'features2': ''},
    '12': {'features': '',
     'level': '',
     'length': '',
     'width': '',
     'description': '',
     'features3': '',
     'features2': ''}},
   'originalPrice': '3550.00',
   'soldDate': '2023-04-18T00:00:00.000Z',
   'occupancy': '',
   'timestamps': {'repliersUpdatedOn': '2023-04-19T21:32:12.000Z',
    'terminatedDate': None,
    'conditionalExpiryDate': None,
    'listingUpdated': '2023-04-19T17:01:48.000Z',
    'extensionEntryDate': None,
    'unavailableDate': '2023-04-18T00:00:00.000Z',
    'expiryDate': '2023-06-23T00:00:00.000Z',
    'listingEntryDate': '2023-03-23T00:00:00.000Z',
    'closedDate': '2023-05-01T00:00:00.000Z',
    'possessionDate': '2023-03-15T00:00:00.000Z',
    'idxUpdated': None,
    'photosUpdated': '2023-03-23T17:28:14.000Z',
    'suspendedDate': None},
   'condominium': {'pets': None,
    'condoCorpNum': None,
    'parkingType': None,
    'fees': {'cableInlc': 'N',
     'waterIncl': 'Y',
     'heatIncl': 'Y',
     'taxesIncl': None,
     'parkingIncl': 'N',
     'maintenance': None,
     'hydroIncl': 'N'},
    'stories': None,
    'propertyMgr': None,
    'lockerLevel': None,
    'unitNumber': None,
    'buildingInsurance': None,
    'locker': None,
    'condoCorp': None,
    'sharesPercentage': None,
    'ensuiteLaundry': None,
    'exposure': None,
    'lockerNumber': '',
    'lockerUnitNumber': None,
    'ammenities': [None, None, None, None, None, None]},
   'taxes': {'annualAmount': '', 'assessmentYear': ''},
   'office': {'brokerageName': 'BERKSHIRE HATHAWAY HOMESERVICES WEST REALTY, BROKERAGE'},
   'type': 'Lease',
   'nearby': {'ammenities': ['Hospital',
     'Park',
     'Public Transit',
     'School',
     '',
     '']},
   'lot': {'depth': '',
    'size': None,
    'width': '',
    'irregular': '',
    'acres': '',
    'legalDescription': '',
    'measurement': ''},
   'mlsNumber': 'W5985741',
   'openHouse': {'1': {'date': '',
     'startTime': '',
     'endTime': '',
     'type': None,
     'status': None},
    '2': {'date': '',
     'startTime': '',
     'endTime': '',
     'type': None,
     'status': None},
    '3': {'date': '',
     'startTime': '',
     'endTime': '',
     'type': None,
     'status': None}},
   'permissions': {'displayAddressOnInternet': 'Y', 'displayPublic': 'N'},
   'soldPrice': '3700.00',
   'details': {'numKitchens': '1',
    'numParkingSpaces': '0.0',
    'laundryLevel': '',
    'zoningDescription': None,
    'moreInformationLink': None,
    'certificationLevel': '',
    'den': 'Y',
    'yearBuilt': '',
    'alternateURLVideoLink': None,
    'exteriorConstruction1': 'Brick',
    'elevator': '',
    'exteriorConstruction2': '',
    'roofMaterial': None,
    'zoning': '',
    'basement1': 'None',
    'basement2': '',
    'sqft': '',
    'handicappedEquipped': '',
    'heating': 'Radiant',
    'numRooms': '6',
    'landscapeFeatures': None,
    'virtualTourUrl': '',
    'landSewer': None,
    'energyCertification': '',
    'numBathrooms': '1',
    'greenPropertyInformationStatement': '',
    'liveStreamEventURL': None,
    'zoningType': None,
    'landAccessType': None,
    'businessSubType': None,
    'numKitchensPlus': '',
    'bathrooms': {'1': {'pieces': '4', 'level': 'Flat', 'count': '1'},
     '2': {'pieces': '', 'level': '', 'count': ''},
     '3': {'pieces': '', 'level': '', 'count': ''},
     '4': {'pieces': '', 'level': '', 'count': ''},
     '5': {'pieces': '', 'level': '', 'count': ''}},
    'swimmingPool': 'None',
    'constructionStyleSplitLevel': None,
    'leaseTerms': '1 Year',
    'numRoomsPlus': '',
    'flooringType': None,
    'farmType': None,
    'landDisposition': None,
    'viewType': None,
    'style': '2-Storey',
    'loadingType': None,
    'numGarageSpaces': '0.0',
    'parkCostMonthly': '',
    'airConditioning': 'Wall Unit',
    'familyRoom': 'Y',
    'constructionStatus': None,
    'numBedrooms': '2',
    'description': 'Architect Designed Luxury 2-Bedroom Apartment In Sought After High Park/Junction! Entirely Renovated, This Historic Detached 2-Storey Home Is On A Quiet Tree-Lined Street. Very Bright Open Concept Kitchen/Living/Dining With Inspiring High Ceilings. Large Modern White Kitchen With European Appliances, Marble Countertops And Slate Floors. Enjoy Outdoor Living And Scenic Views From Private Wood Terrace Facing South And West. Large Living And Dining Room With Views To Front And Back, Gas Fireplace, Entry Cabinet With Plenty Of Storage, Large Slate Bathroom With Soaker Tub And Shower. Office With Street Views. Master Bedroom With Space For King Size Bed And 2nd Bedroom With Space For Queen Size Bed - Both With Built-In Storage. Smoked White Oak Hardwood Floors And Your Own Private Entrance.',
    'extras': 'Conveniently Located Near Junction/Bloor West Village/Roncesvalles. Minutes To Shopping/Great Restaurants/High Park/Ttc. Easy Access To Downtown/Lakeshore/Gardiner. Walking Distance To Up Express/Junction. Owner/Landlord Living Below.',
    'livingAreaMeasurement': None,
    'patio': None,
    'amperage': None,
    'centralAirConditioning': 'N',
    'furnished': 'N',
    'foundationType': None,
    'sewer': 'Sewers',
    'propertyType': 'Detached',
    'HOAFee': None,
    'commonElementsIncluded': 'N',
    'numDrivewaySpaces': None,
    'numBathroomsPlus': None,
    'ceilingType': None,
    'waterSource': 'Municipal',
    'numBedroomsPlus': '1',
    'garage': 'None',
    'centralVac': '',
    'sqftRange': None,
    'driveway': 'None',
    'numFireplaces': 'Y',
    'energuideRating': None,
    'fireProtection': None,
    'storageType': None,
    'analyticsClick': None,
    'businessType': None,
    'numBathroomsHalf': None},
   'class': 'ResidentialProperty',
   'map': {'latitude': '43.6607634',
    'point': 'POINT (-79.4601019 43.6607634)',
    'longitude': '-79.4601019'},
   'images': ['IMG-W5985741_1.jpg',
    'IMG-W5985741_2.jpg',
    'IMG-W5985741_3.jpg',
    'IMG-W5985741_4.jpg',
    'IMG-W5985741_5.jpg',
    'IMG-W5985741_6.jpg',
    'IMG-W5985741_7.jpg',
    'IMG-W5985741_8.jpg',
    'IMG-W5985741_9.jpg',
    'IMG-W5985741_10.jpg',
    'IMG-W5985741_11.jpg',
    'IMG-W5985741_12.jpg',
    'IMG-W5985741_13.jpg',
    'IMG-W5985741_14.jpg',
    'IMG-W5985741_15.jpg'],
   'address': {'area': 'Toronto',
    'zip': 'M6P2G3',
    'country': None,
    'city': 'Toronto',
    'streetNumber': '170',
    'unitNumber': 'Upper',
    'streetDirection': '',
    'streetName': 'Indian Road',
    'streetDirectionPrefix': None,
    'district': 'Toronto W02',
    'streetSuffix': 'Cres',
    'neighborhood': 'High Park North',
    'state': 'Ontario',
    'majorIntersection': 'Glenlake Ave & Indian Rd Cres',
    'communityCode': '01.W02.0440'},
   'resource': 'Property:2381',
   'raw': None,
   'updatedOn': '2023-04-19T17:01:48.000Z',
   'daysOnMarket': '26',
   'agents': [],
   'coopCompensation': 'Half  Month  Rent  +  Hst',
   'listPrice': '3550.00',
   'lastStatus': 'Lsd',
   'status': 'U',
   'boardId': 2}]}

In [ ]:
r.url

'https://api.repliers.io/listings/?mlsNumber=N4418450&mlsNumber=N4435010&mlsNumber=N4437661&mlsNumber=N4405561&mlsNumber=W4426017&mlsNumber=C4432900&mlsNumber=W4356174&mlsNumber=W4424829&mlsNumber=N4424863&mlsNumber=N4406614&mlsNumber=N4425486&mlsNumber=E4424324&mlsNumber=C4433947&mlsNumber=W4424200&mlsNumber=X4439875&mlsNumber=E4430512&mlsNumber=X4430401&mlsNumber=N4423281&mlsNumber=N4422493&mlsNumber=N4429780&mlsNumber=W4438444&mlsNumber=W4437823&mlsNumber=E4425014&mlsNumber=C4425805&mlsNumber=N4429957&mlsNumber=N4437409&mlsNumber=C4438129&mlsNumber=N4437031&mlsNumber=N4438257&mlsNumber=N4438687&mlsNumber=W4438387&mlsNumber=W4414869&mlsNumber=S4414823&mlsNumber=E4413211&mlsNumber=N4435193&mlsNumber=W4436787&mlsNumber=C4436013&mlsNumber=N4434092&mlsNumber=E4434010&mlsNumber=X4436215&mlsNumber=E4435867&mlsNumber=N4435409&mlsNumber=E4435443&mlsNumber=N4431597&mlsNumber=S4432910&mlsNumber=W4435020&mlsNumber=N4433302&mlsNumber=W4432322&mlsNumber=N4432353&mlsNumber=W4428780&mlsNumber=N4431064&mlsNumber=E4421307&mlsNumber=N4422949&mlsNumber=W4420944&mlsNumber=X4421512&mlsNumber=N4422458&mlsNumber=C4424747&mlsNumber=N4433297&mlsNumber=N4434401&mlsNumber=C4433552&mlsNumber=C4374690&mlsNumber=C4376726&mlsNumber=N4372536&mlsNumber=C4388604&mlsNumber=N4390201&mlsNumber=N4398952&mlsNumber=C4402243&mlsNumber=S4403817&mlsNumber=W4401501&mlsNumber=W4407488&mlsNumber=X4407131&mlsNumber=E4380787&mlsNumber=N4383010&mlsNumber=S4372297&mlsNumber=W4409869&mlsNumber=N4407894&mlsNumber=C4414391&mlsNumber=C4430046&mlsNumber=W4373599&mlsNumber=W4436452&mlsNumber=X4418578&mlsNumber=X4424263&mlsNumber=C4413116&mlsNumber=C4419358&mlsNumber=N4434119&mlsNumber=W4391609&mlsNumber=W4365876&mlsNumber=C4425555&mlsNumber=C4424140&mlsNumber=W4425473&mlsNumber=W4435139&mlsNumber=C4378740&mlsNumber=E4413456&mlsNumber=N4434230&mlsNumber=C4399139&mlsNumber=N4399483&mlsNumber=W4406065&mlsNumber=N4412192&mlsNumber=W4398250&mlsNumber=W4394072&mlsNumber=E4430480&mlsNumber=N4424979&mlsNumber=W4384228&mlsNumber=C4415065&mlsNumber=W4431860&mlsNumber=E4431017&mlsNumber=W4414890&mlsNumber=E4432767&mlsNumber=W4425210&mlsNumber=C4424219&mlsNumber=C4436287&mlsNumber=C4433149&mlsNumber=C4420840&mlsNumber=C4423651&mlsNumber=C4416138&mlsNumber=N4438126&mlsNumber=W4434384&mlsNumber=W4418490&mlsNumber=C4429585&mlsNumber=W4428758&mlsNumber=W4430187&mlsNumber=C4436989&mlsNumber=C4414752&mlsNumber=C4428007&mlsNumber=C4398655&mlsNumber=C4427015&mlsNumber=C4434903&mlsNumber=C4436366&mlsNumber=C4397623&mlsNumber=N4432862&mlsNumber=C4427130&mlsNumber=W4438068&mlsNumber=C4436136&mlsNumber=C4429108&mlsNumber=W4432387&mlsNumber=C4436669&mlsNumber=C4412555&mlsNumber=C4405568&mlsNumber=N4443063&mlsNumber=W4429212&mlsNumber=N4432552&mlsNumber=N4436578&mlsNumber=C4430486&mlsNumber=C4433419&mlsNumber=C4435372&mlsNumber=W4436181&mlsNumber=C4413237&mlsNumber=C4436661&mlsNumber=S4434893&mlsNumber=C4434828&mlsNumber=W4438243&mlsNumber=C4431221&mlsNumber=N4422824&mlsNumber=C4426816&mlsNumber=N4419448&mlsNumber=N4435606&mlsNumber=C4434045&mlsNumber=N4391635&mlsNumber=N4434753&mlsNumber=N4404214&mlsNumber=W4437381&mlsNumber=W4430992&mlsNumber=W4427551&mlsNumber=C4365790&mlsNumber=C4414815&mlsNumber=W4435429&mlsNumber=W4435864&mlsNumber=W4419523&mlsNumber=C4398006&mlsNumber=C4436684&mlsNumber=C4347712&mlsNumber=C4431456&mlsNumber=C4413331&mlsNumber=C4401635&mlsNumber=C4404068&mlsNumber=N4404742&mlsNumber=W4415782&mlsNumber=C4429929&mlsNumber=W4423310&mlsNumber=C4420794&mlsNumber=C4436119&mlsNumber=W4398189&mlsNumber=W4436920&mlsNumber=E4428292&mlsNumber=W4429193&mlsNumber=C4421778&mlsNumber=C4412719&mlsNumber=C4399911&mlsNumber=C4438556&mlsNumber=N4418819&mlsNumber=C4437416&mlsNumber=E4387308&mlsNumber=C4420606&mlsNumber=N4398608&mlsNumber=C4405852&mlsNumber=C4437324&mlsNumber=C4429385&mlsNumber=N4433041&mlsNumber=C4376037&mlsNumber=W4432363&mlsNumber=W4423984&mlsNumber=W4406887&mlsNumber=C4402474&mlsNumber=C4429896&mlsNumber=C4381017&mlsNumber=C4418664&mlsNumber=W4423712&mlsNumber=C4432150&mlsNumber=C4433294&mlsNumber=C4427097&mlsNumber=C4424883&mlsNumber=C4433962&mlsNumber=C4435928&mlsNumber=W4426231&mlsNumber=C4438449&mlsNumber=C4433047&mlsNumber=W4434027&mlsNumber=C4414754&mlsNumber=C4436278&mlsNumber=C4437564&mlsNumber=C4422966&mlsNumber=C4436540&mlsNumber=C4438193&mlsNumber=W4431801&mlsNumber=E4428429&mlsNumber=E4438332&mlsNumber=W4429264&mlsNumber=N4408392&mlsNumber=N4419434&mlsNumber=N4420716&mlsNumber=W4427072&mlsNumber=N4426105&mlsNumber=N4429836&mlsNumber=N4430441&mlsNumber=C4423699&mlsNumber=E4430138&mlsNumber=N4430064&mlsNumber=C4429003&mlsNumber=N4436810&mlsNumber=C4430744&mlsNumber=E4416247&mlsNumber=N4435399&mlsNumber=N4435966&mlsNumber=W4434585&mlsNumber=W4436552&mlsNumber=W4435493&mlsNumber=C4435601&mlsNumber=X4433113&mlsNumber=E4432270&mlsNumber=W4434743&mlsNumber=N4432299&mlsNumber=N4419295&mlsNumber=N4418921&mlsNumber=C4422230&mlsNumber=E4422751&mlsNumber=N4420862&mlsNumber=N4421905&mlsNumber=W4435963&mlsNumber=N4435017&mlsNumber=W4434803&mlsNumber=X4387305&mlsNumber=C4367430&mlsNumber=E4399740&mlsNumber=C4399834&mlsNumber=C4399225&mlsNumber=N4400769&mlsNumber=E4394969&mlsNumber=X4406930&mlsNumber=N4404607&mlsNumber=C4400988&mlsNumber=C4407959&mlsNumber=E4414003&mlsNumber=W4416204&mlsNumber=C4433625&mlsNumber=W4434405&mlsNumber=E4435557&mlsNumber=N4435968&mlsNumber=N4431861&mlsNumber=C4433660&mlsNumber=W4418551&mlsNumber=C4426826&mlsNumber=W4438849&mlsNumber=C4426725&mlsNumber=C4435107&mlsNumber=W4431018&mlsNumber=C4428609&mlsNumber=N4434614&mlsNumber=C4327290&mlsNumber=C4431486&mlsNumber=C4429211&mlsNumber=C4416100&mlsNumber=C4421829&mlsNumber=C4431945&mlsNumber=C4428586&mlsNumber=C4431050&mlsNumber=C4424379&mlsNumber=W4408262&mlsNumber=W4437016&mlsNumber=W4414743&mlsNumber=W4423523&mlsNumber=C4436560&mlsNumber=C4405828&mlsNumber=N4427082&mlsNumber=W4435084&mlsNumber=W4431372&mlsNumber=C4378286&mlsNumber=C4438187&mlsNumber=W4418802&mlsNumber=C4410341&mlsNumber=C4436345&mlsNumber=C4432853&mlsNumber=W4436596&mlsNumber=C4414169&mlsNumber=C4418255&mlsNumber=C4387505&mlsNumber=E4418680&mlsNumber=W4434665&mlsNumber=W4433216&mlsNumber=C4427579&mlsNumber=C4432626&mlsNumber=C4394002&mlsNumber=N4434772&mlsNumber=C4431583&mlsNumber=W4434525&mlsNumber=W4428416&mlsNumber=C4436433&mlsNumber=C4424738&mlsNumber=C4433326&mlsNumber=W4433640&mlsNumber=C4432469&mlsNumber=C4355705&mlsNumber=C4424718&mlsNumber=C4429636&mlsNumber=N4430035&mlsNumber=N4377345&mlsNumber=C4429821&mlsNumber=C4423842&mlsNumber=N4436407&mlsNumber=S4389311&mlsNumber=W4436803&mlsNumber=E4422802&mlsNumber=C4430669&mlsNumber=E4399943&mlsNumber=S4424428&mlsNumber=W4429544&mlsNumber=W4424622&mlsNumber=C4423358&mlsNumber=S4423859&mlsNumber=W4428812&mlsNumber=W4423517&mlsNumber=E4427926&mlsNumber=C4427803&mlsNumber=C4437239&mlsNumber=C4437188&mlsNumber=N4435603&mlsNumber=C4434718&mlsNumber=N4433802&mlsNumber=N4434454&mlsNumber=N4433227&mlsNumber=C4432457&mlsNumber=N4433193&mlsNumber=N4431489&mlsNumber=C4432337&mlsNumber=W4412932&mlsNumber=N4410580&mlsNumber=W4431317&mlsNumber=E4421972&mlsNumber=N4428540&mlsNumber=W4423187&mlsNumber=W4435011&mlsNumber=N4384702&mlsNumber=W4393351&mlsNumber=N4398067&mlsNumber=S4389905&mlsNumber=E4398759&mlsNumber=W4405982&mlsNumber=E4406815&mlsNumber=C4377694&mlsNumber=C4409976&mlsNumber=E4408503&mlsNumber=W4408820&mlsNumber=W4414282&mlsNumber=W4419820&mlsNumber=C4434731&mlsNumber=W4401846&mlsNumber=N4422919&mlsNumber=E4421847&mlsNumber=E4398836&mlsNumber=N4434645&mlsNumber=W4433343&mlsNumber=W4387006&mlsNumber=E4430930&mlsNumber=C4421381&mlsNumber=N4426274&mlsNumber=W4437691&mlsNumber=C4434767&mlsNumber=C4429715&mlsNumber=W4433899&mlsNumber=C4434350&mlsNumber=C4428027&status=U&lastStatus=Lsd'

In [ ]:
data

rough

In [ ]:
url = "https://api.repliers.io/listings?map=%5B%5B%5B44.439648999999996%2C%20-79.73452499999999%5D%2C%0A%20%20%5B44.439648999999996%2C%20-79.634525%5D%2C%0A%20%20%5B44.339649%2C%20-79.634525%5D%2C%0A%20%20%5B44.339649%2C%20-79.73452499999999%5D%2C%0A%20%20%5B44.439648999999996%2C%20-79.73452499999999%5D%5D%5D"

In [ ]:
outlst = [([str(c) for c in top_left])]

def turn_string(lst):
    return [str(c) for c in lst]

In [ ]:
coords = [[[-79.14121,43.79041],[-79.132627,43.773059],[-79.188932,43.886988],[-79.200605,43.877832],[-79.236654,43.869665],[-79.265836,43.860011],[-79.281972,43.856051],[-79.322828,43.84689],[-79.368146,43.839214],[-79.386021,43.836139],[-79.41486,43.838616],[-79.423787,43.836635],[-79.475285,43.82227],[-79.480092,43.813352],[-79.480778,43.803441],[-79.485585,43.79799],[-79.493825,43.794025],[-79.556996,43.779649],[-79.601628,43.761303],[-79.61611,43.758572],[-79.629934,43.750141],[-79.625471,43.728064],[-79.616888,43.713177],[-79.606245,43.695555],[-79.601095,43.685873],[-79.593885,43.681156],[-79.590109,43.672465],[-79.582212,43.671224],[-79.574659,43.670975],[-79.535177,43.58325],[-79.424627,43.619052],[-79.385488,43.602645],[-79.315451,43.612092],[-79.14121,43.79041]]]

In [ ]:
# top_left = [44.389649+0.05, -79.684525-0.05]
# top_right = [44.389649+0.05, -79.684525+0.05]
# bottom_right = [44.389649-0.05, -79.684525+0.05]
# bottom_left = [44.389649-0.05, -79.684525-0.05]

#coords = [[top_left, top_right, bottom_right, bottom_left, top_left]]

url = f"https://api.repliers.io/listings/"
#payload = {"map": coords, "status": 'U'}
payload = {
"map": [
[
[
-79.39010775366981,
43.65576424783316
],
[
-79.39357890073602,
43.64856703742666
],
[
-79.38311365137208,
43.647667325480626
],
[
-79.37440987962434,
43.65059134003147
],
[
-79.3750315776063,
43.65969985745275
],
[
-79.38674022293412,
43.661798743774085
],
[
-79.39010775366981,
43.65576424783316
]
]
]
}
headers = {'repliers-api-key': os.environ['REPLIERS_KEY']}
r = requests.request("POST",url, params=payload, headers=headers)
#print(r)
data = r.json()

In [ ]:
r.url

'https://api.repliers.io/listings/?map=%5B%2744.439648999999996%27%2C+%27-79.73452499999999%27%5D&map=%5B%2744.439648999999996%27%2C+%27-79.634525%27%5D&map=%5B%2744.339649%27%2C+%27-79.634525%27%5D&map=%5B%2744.339649%27%2C+%27-79.73452499999999%27%5D&map=%5B%2744.439648999999996%27%2C+%27-79.73452499999999%27%5D'

In [ ]:
data

In [ ]:
numbers = ['W5965967', 'W5985741', 'C5975287', 'C6024761', 'S6014669']

In [ ]:
r.url

'https://api.repliers.io/listings/?map=%5B%2744.439648999999996%27%2C+%27-79.73452499999999%27%5D&map=%5B%2744.439648999999996%27%2C+%27-79.634525%27%5D&map=%5B%2744.339649%27%2C+%27-79.634525%27%5D&map=%5B%2744.339649%27%2C+%27-79.73452499999999%27%5D&map=%5B%2744.439648999999996%27%2C+%27-79.73452499999999%27%5D'

In [ ]:
url = f"https://api.repliers.io/listings/"
payload = {"mlsNumber": numbers, "status": ["U"], "lastStatus": "Lsd"}
payload = {}
headers = {'repliers-api-key': os.environ['REPLIERS_KEY']}
r = requests.request("GET",url, params=payload, headers=headers)
#print(r)
data = r.json()

data

In [ ]:
url = f"https://api.repliers.io/listings/"
payload = {"mlsNumber": numbers, "status": ["U"], "lastStatus": "Lsd"}
headers = {'repliers-api-key': os.environ['REPLIERS_KEY']}
r = requests.request("GET",url, params=payload, headers=headers)
#print(r)
data = r.json()

In [ ]:
r.url

'https://api.repliers.io/listings/?mlsNumber=W5965967&mlsNumber=W5985741&mlsNumber=C5975287&mlsNumber=C6024761&mlsNumber=S6014669&status=U'

In [ ]:
import requests
import json
url = "https://api.repliers.io/listings"
headers = {
"repliers-api-key": os.environ['REPLIERS_KEY'],
"Content-Type": "application/json"
}
data = {
"map": 
coords
}
response = requests.request("GET",url, headers=headers, params=json.dumps(data))
print(response.status_code)
print(response.json())

200

In [ ]:
json.dumps(data)

'{"map": [[[44.439648999999996, -79.73452499999999], [44.439648999999996, -79.634525], [44.339649, -79.634525], [44.339649, -79.73452499999999], [44.439648999999996, -79.73452499999999]]]}'

In [ ]:
sale = pd.read_csv(os.getcwd()+"\\data\\raw_sale_data.csv")

In [ ]:
len(sale)

514720

In [ ]:
import asyncio

lst = [1,2,3,4,5,6,7,8,9]

async def counta(lst):
    final = []
    for i in range(len(lst)):
        print(lst[i])
        await asyncio.sleep(1)
        print(lst[i]/2)
        final.append(lst[i]/2)
    return final

async def main():
    final = await asyncio.gather(counta(lst), counta(lst))
    return

final = await main()

1
1
0.5
2
0.5
2
1.0
3
1.0
3
1.5
4
1.5
4
2.0
5
2.0
5
2.5
6
2.5
6
3.0
7
3.0
7
3.5
8
3.5
8
4.0
9
4.0
9
4.5
4.5

In [ ]:
final

[[0.5, 1.0, 1.5, 2.0, 2.5, 3.0, 3.5, 4.0, 4.5],
 [0.5, 1.0, 1.5, 2.0, 2.5, 3.0, 3.5, 4.0, 4.5]]

In [ ]:
async def grab_avg_prices(df):
    pass

In [ ]:
def test_get_avg_comparables(df):
    mlsNumbers = df['mlsNumber'].values[:400]
    avg_prices = []

    url = f"https://api.repliers.io/listings?resultsPerPage=10000"

    payload = {'mlsNumber': mlsNumbers, 'status': 'U', 'lastStatus': 'Lsd'}
    headers = {'repliers-api-key': os.environ['REPLIERS_KEY']}
    r = requests.request("GET",url, params=payload, headers=headers)
    print(r)
    data = r.json()
    return data

In [ ]:
data = test_get_avg_comparables(lease_df)

<Response [200]>

In [ ]:
data

{'page': 1,
 'numPages': 1,
 'pageSize': 10000,
 'count': 400,
 'statistics': {'listPrice': {'min': 1000, 'max': 12500}},
 'listings': [{'listDate': '2019-04-16T00:00:00.000Z',
   'images': ['IMG-N4418450_1.jpg',
    'IMG-N4418450_2.jpg',
    'IMG-N4418450_3.jpg',
    'IMG-N4418450_4.jpg',
    'IMG-N4418450_5.jpg',
    'IMG-N4418450_6.jpg',
    'IMG-N4418450_7.jpg',
    'IMG-N4418450_8.jpg',
    'IMG-N4418450_9.jpg'],
   'address': {'area': 'York',
    'zip': 'L3Y0E1',
    'country': None,
    'city': 'Newmarket',
    'streetNumber': '15',
    'unitNumber': '',
    'streetDirection': '',
    'streetName': 'Heswall',
    'district': 'Newmarket',
    'streetSuffix': 'Lane',
    'neighborhood': 'Glenway Estates',
    'state': 'Ontario',
    'majorIntersection': 'Yonge/ Davis',
    'communityCode': '09.07.0020'},
   'soldDate': '2019-05-06T00:00:00.000Z',
   'resource': 'Property:2381',
   'timestamps': {'listingUpdated': '2019-05-08T10:56:42.000Z'},
   'type': 'Lease',
   'mlsNumber': 'N4418450',
   'permissions': {'displayAddressOnInternet': 'Y', 'displayPublic': 'N'},
   'soldPrice': '2200.00',
   'details': {'numBathrooms': '4',
    'numBedrooms': '4',
    'sqft': '1500-2000',
    'style': '3-Storey',
    'yearBuilt': '0-5',
    'numBathroomsPlus': None},
   'class': 'ResidentialProperty',
   'map': {'latitude': '44.05193999999999', 'longitude': '-79.49083999999999'},
   'listPrice': '2100.00',
   'lastStatus': 'Lsd',
   'status': 'U',
   'boardId': 2,
   'agents': []},
  {'listDate': '2019-05-01T00:00:00.000Z',
   'images': ['IMG-N4435010_1.jpg',
    'IMG-N4435010_2.jpg',
    'IMG-N4435010_3.jpg',
    'IMG-N4435010_4.jpg',
    'IMG-N4435010_5.jpg',
    'IMG-N4435010_6.jpg',
    'IMG-N4435010_7.jpg',
    'IMG-N4435010_8.jpg',
    'IMG-N4435010_9.jpg'],
   'address': {'area': 'York',
    'zip': 'L4H1T3',
    'country': None,
    'city': 'Vaughan',
    'streetNumber': '72',
    'unitNumber': '',
    'streetDirection': '',
    'streetName': 'Monte Carlo',
    'district': 'Vaughan',
    'streetSuffix': 'Dr',
    'neighborhood': 'Sonoma Heights',
    'state': 'Ontario',
    'majorIntersection': 'Islington and Rutherford',
    'communityCode': '09.02.0030'},
   'soldDate': '2019-05-06T00:00:00.000Z',
   'resource': 'Property:2381',
   'timestamps': {'listingUpdated': '2019-05-08T15:58:16.000Z'},
   'type': 'Lease',
   'mlsNumber': 'N4435010',
   'permissions': {'displayAddressOnInternet': 'Y', 'displayPublic': 'N'},
   'soldPrice': '1350.00',
   'details': {'numBathrooms': '1',
    'numBedrooms': '2',
    'sqft': '',
    'style': '2-Storey',
    'yearBuilt': '16-30',
    'numBathroomsPlus': None},
   'class': 'ResidentialProperty',
   'map': {'latitude': '43.8168699', 'longitude': '-79.618265'},
   'listPrice': '1350.00',
   'lastStatus': 'Lsd',
   'status': 'U',
   'boardId': 2,
   'agents': []},
  {'listDate': '2019-05-03T00:00:00.000Z',
   'images': ['IMG-N4437661_1.jpg',
    'IMG-N4437661_2.jpg',
    'IMG-N4437661_3.jpg',
    'IMG-N4437661_4.jpg',
    'IMG-N4437661_5.jpg',
    'IMG-N4437661_6.jpg',
    'IMG-N4437661_7.jpg',
    'IMG-N4437661_8.jpg',
    'IMG-N4437661_9.jpg',
    'IMG-N4437661_10.jpg',
    'IMG-N4437661_11.jpg',
    'IMG-N4437661_12.jpg',
    'IMG-N4437661_13.jpg',
    'IMG-N4437661_14.jpg',
    'IMG-N4437661_15.jpg'],
   'address': {'area': 'York',
    'zip': 'L4E0T9',
    'country': None,
    'city': 'Richmond Hill',
    'streetNumber': '148',
    'unitNumber': '',
    'streetDirection': '',
    'streetName': 'Riding Mountain',
    'district': 'Richmond Hill',
    'streetSuffix': 'Dr',
    'neighborhood': 'Jefferson',
    'state': 'Ontario',
    'majorIntersection': 'Yonge/19th Ave',
    'communityCode': '09.04.0020'},
   'soldDate': '2019-05-06T00:00:00.000Z',
   'resource': 'Property:2381',
   'timestamps': {'listingUpdated': '2019-05-07T11:06:02.000Z'},
   'type': 'Lease',
   'mlsNumber': 'N4437661',
   'permissions': {'displayAddressOnInternet': 'Y', 'displayPublic': 'N'},
   'soldPrice': '3000.00',
   'details': {'numBathrooms': '4',
    'numBedrooms': '5',
    'sqft': '3000-3500',
    'style': '2-Storey',
    'yearBuilt': '0-5',
    'numBathroomsPlus': None},
   'class': 'ResidentialProperty',
   'map': {'latitude': '43.9175319', 'longitude': '-79.43661039999999'},
   'listPrice': '2999.00',
   'lastStatus': 'Lsd',
   'status': 'U',
   'boardId': 2,
   'agents': []},
  {'listDate': '2019-04-03T00:00:00.000Z',
   'images': ['IMG-N4405561_1.jpg',
    'IMG-N4405561_2.jpg',
    'IMG-N4405561_3.jpg',
    'IMG-N4405561_4.jpg',
    'IMG-N4405561_5.jpg',
    'IMG-N4405561_6.jpg',
    'IMG-N4405561_7.jpg',
    'IMG-N4405561_8.jpg',
    'IMG-N4405561_9.jpg',
    'IMG-N4405561_10.jpg'],
   'address': {'area': 'York',
    'zip': 'L9N 0T3',
    'country': None,
    'city': 'East Gwillimbury',
    'streetNumber': '6',
    'unitNumber': '',
    'streetDirection': '',
    'streetName': 'Tesla',
    'district': 'East Gwillimbury',
    'streetSuffix': 'Cres',
    'neighborhood': 'Holland Landing',
    'state': 'Ontario',
    'majorIntersection': 'Yonge & Green Lane',
    'communityCode': '09.08.0010'},
   'soldDate': '2019-05-06T00:00:00.000Z',
   'resource': 'Property:2381',
   'timestamps': {'listingUpdated': '2019-05-08T14:23:19.000Z'},
   'type': 'Lease',
   'mlsNumber': 'N4405561',
   'permissions': {'displayAddressOnInternet': 'Y', 'displayPublic': 'N'},
   'soldPrice': '2400.00',
   'details': {'numBathrooms': '4',
    'numBedrooms': '4',
    'sqft': '3000-3500',
    'style': '2-Storey',
    'yearBuilt': 'New',
    'numBathroomsPlus': None},
   'class': 'ResidentialProperty',
   'map': {'latitude': '44.09185', 'longitude': '-79.50193'},
   'listPrice': '2400.00',
   'lastStatus': 'Lsd',
   'status': 'U',
   'boardId': 2,
   'agents': []},
  {'listDate': '2019-04-24T00:00:00.000Z',
   'images': ['IMG-W4426017_1.jpg'],
   'address': {'area': 'Peel',
    'zip': 'L4X4H2',
    'country': None,
    'city': 'Mississauga',
    'streetNumber': '4755',
    'unitNumber': '',
    'streetDirection': '',
    'streetName': 'James Austin',
    'district': 'Mississauga',
    'streetSuffix': 'Dr',
    'neighborhood': 'Hurontario',
    'state': 'Ontario',
    'majorIntersection': 'Hurontario/Eglinton',
    'communityCode': '05.03.0200'},
   'soldDate': '2019-05-06T00:00:00.000Z',
   'resource': 'Property:2381',
   'timestamps': {'listingUpdated': '2019-05-09T13:23:15.000Z'},
   'type': 'Lease',
   'mlsNumber': 'W4426017',
   'permissions': {'displayAddressOnInternet': 'Y', 'displayPublic': 'N'},
   'soldPrice': '3400.00',
   'details': {'numBathrooms': '4',
    'numBedrooms': '4',
    'sqft': '',
    'style': '2-Storey',
    'yearBuilt': '',
    'numBathroomsPlus': None},
   'class': 'ResidentialProperty',
   'map': {'latitude': '43.6064424', 'longitude': '-79.6422499'},
   'listPrice': '3400.00',
   'lastStatus': 'Lsd',
   'status': 'U',
   'boardId': 2,
   'agents': []},
  {'listDate': '2019-04-30T00:00:00.000Z',
   'images': ['IMG-C4432900_1.jpg'],
   'address': {'area': 'Toronto',
    'zip': 'M2P1C2',
    'country': None,
    'city': 'Toronto',
    'streetNumber': '66',
    'unitNumber': '',
    'streetDirection': '',
    'streetName': 'Munro',
    'district': 'Toronto C12',
    'streetSuffix': 'Blvd',
    'neighborhood': 'St. Andrew-Windfields',
    'state': 'Ontario',
    'majorIntersection': 'Bayview/York Mills',
    'communityCode': '01.C12.0640'},
   'soldDate': '2019-05-06T00:00:00.000Z',
   'resource': 'Property:2381',
   'timestamps': {'listingUpdated': '2019-05-07T12:59:58.000Z'},
   'type': 'Lease',
   'mlsNumber': 'C4432900',
   'permissions': {'displayAddressOnInternet': 'Y', 'displayPublic': 'N'},
   'soldPrice': '4800.00',
   'details': {'numBathrooms': '3',
    'numBedrooms': '3',
    'sqft': '',
    'style': 'Bungalow',
    'yearBuilt': '',
    'numBathroomsPlus': None},
   'class': 'ResidentialProperty',
   'map': {'latitude': '43.7468834', 'longitude': '-79.3951895'},
   'listPrice': '4800.00',
   'lastStatus': 'Lsd',
   'status': 'U',
   'boardId': 2,
   'agents': []},
  {'listDate': '2019-02-08T00:00:00.000Z',
   'images': ['IMG-W4356174_1.jpg',
    'IMG-W4356174_2.jpg',
    'IMG-W4356174_3.jpg',
    'IMG-W4356174_4.jpg',
    'IMG-W4356174_5.jpg',
    'IMG-W4356174_6.jpg',
    'IMG-W4356174_7.jpg',
    'IMG-W4356174_8.jpg',
    'IMG-W4356174_9.jpg',
    'IMG-W4356174_10.jpg',
    'IMG-W4356174_11.jpg',
    'IMG-W4356174_12.jpg',
    'IMG-W4356174_13.jpg',
    'IMG-W4356174_14.jpg',
    'IMG-W4356174_15.jpg',
    'IMG-W4356174_16.jpg',
    'IMG-W4356174_17.jpg',
    'IMG-W4356174_18.jpg',
    'IMG-W4356174_19.jpg',
    'IMG-W4356174_20.jpg'],
   'address': {'area': 'Halton',
    'zip': 'L6H0T6',
    'country': None,
    'city': 'Oakville',
    'streetNumber': '3226',
    'unitNumber': '',
    'streetDirection': '',
    'streetName': 'William Rose',
    'district': 'Oakville',
    'streetSuffix': 'Way',
    'neighborhood': 'Rural Oakville',
    'state': 'Ontario',
    'majorIntersection': 'Dundas/8th Line',
    'communityCode': '06.04.0060'},
   'soldDate': '2019-05-06T00:00:00.000Z',
   'resource': 'Property:2381',
   'timestamps': {'listingUpdated': '2019-05-07T23:11:44.000Z'},
   'type': 'Lease',
   'mlsNumber': 'W4356174',
   'permissions': {'displayAddressOnInternet': 'Y', 'displayPublic': 'N'},
   'soldPrice': '3600.00',
   'details': {'numBathrooms': '5',
    'numBedrooms': '4',
    'sqft': '3000-3500',
    'style': '2-Storey',
    'yearBuilt': 'New',
    'numBathroomsPlus': None},
   'class': 'ResidentialProperty',
   'map': {'latitude': '43.4981375', 'longitude': '-79.7220875'},
   'listPrice': '3600.00',
   'lastStatus': 'Lsd',
   'status': 'U',
   'boardId': 2,
   'agents': []},
  {'listDate': '2019-04-22T00:00:00.000Z',
   'images': ['IMG-W4424829_1.jpg',
    'IMG-W4424829_2.jpg',
    'IMG-W4424829_3.jpg',
    'IMG-W4424829_4.jpg',
    'IMG-W4424829_5.jpg',
    'IMG-W4424829_6.jpg',
    'IMG-W4424829_7.jpg',
    'IMG-W4424829_8.jpg',
    'IMG-W4424829_9.jpg',
    'IMG-W4424829_10.jpg',
    'IMG-W4424829_11.jpg',
    'IMG-W4424829_12.jpg',
    'IMG-W4424829_13.jpg',
    'IMG-W4424829_14.jpg',
    'IMG-W4424829_15.jpg',
    'IMG-W4424829_16.jpg',
    'IMG-W4424829_17.jpg',
    'IMG-W4424829_18.jpg',
    'IMG-W4424829_19.jpg',
    'IMG-W4424829_20.jpg'],
   'address': {'area': 'Halton',
    'zip': 'L7N 1X2',
    'country': None,
    'city': 'Burlington',
    'streetNumber': '342',
    'unitNumber': '',
    'streetDirection': '',
    'streetName': 'Oakwood',
    'district': 'Burlington',
    'streetSuffix': 'Dr',
    'neighborhood': 'Roseland',
    'state': 'Ontario',
    'majorIntersection': 'Spruce/Oakwood',
    'communityCode': '06.02.0120'},
   'soldDate': '2019-05-06T00:00:00.000Z',
   'resource': 'Property:2381',
   'timestamps': {'listingUpdated': '2019-05-06T15:26:07.000Z'},
   'type': 'Lease',
   'mlsNumber': 'W4424829',
   'permissions': {'displayAddressOnInternet': 'Y', 'displayPublic': 'N'},
   'soldPrice': '3600.00',
   'details': {'numBathrooms': '3',
    'numBedrooms': '4',
    'sqft': '',
    'style': 'Sidesplit 4',
    'yearBuilt': '',
    'numBathroomsPlus': None},
   'class': 'ResidentialProperty',
   'map': {'latitude': '43.3450861', 'longitude': '-79.7721256'},
   'listPrice': '3600.00',
   'lastStatus': 'Lsd',
   'status': 'U',
   'boardId': 2,
   'agents': []},
  {'listDate': '2019-04-23T00:00:00.000Z',
   'images': ['IMG-N4424863_1.jpg',
    'IMG-N4424863_2.jpg',
    'IMG-N4424863_3.jpg',
    'IMG-N4424863_4.jpg',
    'IMG-N4424863_5.jpg',
    'IMG-N4424863_6.jpg',
    'IMG-N4424863_7.jpg',
    'IMG-N4424863_8.jpg',
    'IMG-N4424863_9.jpg',
    'IMG-N4424863_10.jpg',
    'IMG-N4424863_11.jpg',
    'IMG-N4424863_12.jpg',
    'IMG-N4424863_13.jpg',
    'IMG-N4424863_14.jpg',
    'IMG-N4424863_15.jpg'],
   'address': {'area': 'Simcoe',
    'zip': 'L3Z 0X1',
    'country': None,
    'city': 'Bradford West Gwillimbury',
    'streetNumber': '214',
    'unitNumber': '',
    'streetDirection': '',
    'streetName': 'Gibson',
    'district': 'Bradford West Gwillimbury',
    'streetSuffix': 'Circ',
    'neighborhood': 'Bradford',
    'state': 'Ontario',
    'majorIntersection': 'Simcoe Rd & Line 6',
    'communityCode': '04.13.0030'},
   'soldDate': '2019-05-06T00:00:00.000Z',
   'resource': 'Property:2381',
   'timestamps': {'listingUpdated': '2019-05-10T14:14:00.000Z'},
   'type': 'Lease',
   'mlsNumber': 'N4424863',
   'permissions': {'displayAddressOnInternet': 'Y', 'displayPublic': 'N'},
   'soldPrice': '2200.00',
   'details': {'numBathrooms': '4',
    'numBedrooms': '4',
    'sqft': '2500-3000',
    'style': '2-Storey',
    'yearBuilt': 'New',
    'numBathroomsPlus': None},
   'class': 'ResidentialProperty',
   'map': {'latitude': '44.0952303', 'longitude': '-79.5717308'},
   'listPrice': '2200.00',
   'lastStatus': 'Lsd',
   'status': 'U',
   'boardId': 2,
   'agents': []},
  {'listDate': '2019-04-03T00:00:00.000Z',
   'images': ['IMG-N4406614_1.jpg',
    'IMG-N4406614_2.jpg',
    'IMG-N4406614_3.jpg',
    'IMG-N4406614_4.jpg',
    'IMG-N4406614_5.jpg',
    'IMG-N4406614_6.jpg',
    'IMG-N4406614_7.jpg',
    'IMG-N4406614_8.jpg',
    'IMG-N4406614_9.jpg',
    'IMG-N4406614_10.jpg'],
   'address': {'area': 'York',
    'zip': 'L3X3W9',
    'country': None,
    'city': 'Markham',
    'streetNumber': '32',
    'unitNumber': '',
    'streetDirection': '',
    'streetName': 'Blue Spruce',
    'district': 'Markham',
    'streetSuffix': 'Lane',
    'neighborhood': 'Royal Orchard',
    'state': 'Ontario',
    'majorIntersection': 'Yonge and Royal Orchard',
    'communityCode': '09.03.0020'},
   'soldDate': '2019-05-06T00:00:00.000Z',
   'resource': 'Property:2381',
   'timestamps': {'listingUpdated': '2019-05-08T15:35:23.000Z'},
   'type': 'Lease',
   'mlsNumber': 'N4406614',
   'permissions': {'displayAddressOnInternet': 'Y', 'displayPublic': 'N'},
   'soldPrice': '2150.00',
   'details': {'numBathrooms': '1',
    'numBedrooms': '3',
    'sqft': '',
    'style': 'Backsplit 4',
    'yearBuilt': '',
    'numBathroomsPlus': None},
   'class': 'ResidentialProperty',
   'map': {'latitude': '43.82614600000001', 'longitude': '-79.4073715'},
   'listPrice': '2190.00',
   'lastStatus': 'Lsd',
   'status': 'U',
   'boardId': 2,
   'agents': []},
  {'listDate': '2019-04-22T00:00:00.000Z',
   'images': ['IMG-N4425486_1.jpg',
    'IMG-N4425486_2.jpg',
    'IMG-N4425486_3.jpg',
    'IMG-N4425486_4.jpg',
    'IMG-N4425486_5.jpg',
    'IMG-N4425486_6.jpg',
    'IMG-N4425486_7.jpg',
    'IMG-N4425486_8.jpg',
    'IMG-N4425486_9.jpg',
    'IMG-N4425486_10.jpg',
    'IMG-N4425486_11.jpg'],
   'address': {'area': 'York',
    'zip': 'L3S3N5',
    'country': None,
    'city': 'Markham',
    'streetNumber': '54',
    'unitNumber': '',
    'streetDirection': '',
    'streetName': 'Laird',
    'district': 'Markham',
    'streetSuffix': 'Dr',
    'neighborhood': 'Middlefield',
    'state': 'Ontario',
    'majorIntersection': 'Markham Rd/Steeles',
    'communityCode': '09.03.0280'},
   'soldDate': '2019-05-06T00:00:00.000Z',
   'resource': 'Property:2381',
   'timestamps': {'listingUpdated': '2019-05-15T15:57:35.000Z'},
   'type': 'Lease',
   'mlsNumber': 'N4425486',
   'permissions': {'displayAddressOnInternet': 'Y', 'displayPublic': 'N'},
   'soldPrice': '2200.00',
   'details': {'numBathrooms': '2',
    'numBedrooms': '3',
    'sqft': '',
    'style': '2-Storey',
    'yearBuilt': '',
    'numBathroomsPlus': None},
   'class': 'ResidentialProperty',
   'map': {'latitude': '43.836296', 'longitude': '-79.255386'},
   'listPrice': '2200.00',
   'lastStatus': 'Lsd',
   'status': 'U',
   'boardId': 2,
   'agents': []},
  {'listDate': '2019-04-23T00:00:00.000Z',
   'images': ['IMG-E4424324_1.jpg',
    'IMG-E4424324_2.jpg',
    'IMG-E4424324_3.jpg',
    'IMG-E4424324_4.jpg',
    'IMG-E4424324_5.jpg',
    'IMG-E4424324_6.jpg',
    'IMG-E4424324_7.jpg',
    'IMG-E4424324_8.jpg',
    'IMG-E4424324_9.jpg',
    'IMG-E4424324_10.jpg',
    'IMG-E4424324_11.jpg',
    'IMG-E4424324_12.jpg',
    'IMG-E4424324_13.jpg',
    'IMG-E4424324_14.jpg',
    'IMG-E4424324_15.jpg',
    'IMG-E4424324_16.jpg',
    'IMG-E4424324_17.jpg'],
   'address': {'area': 'Toronto',
    'zip': 'M4K3A4',
    'country': None,
    'city': 'Toronto',
    'streetNumber': '122',
    'unitNumber': 'Upper',
    'streetDirection': '',
    'streetName': 'Arundel',
    'district': 'Toronto E03',
    'streetSuffix': 'Ave',
    'neighborhood': 'Playter Estates-Danforth',
    'state': 'Ontario',
    'majorIntersection': 'Danforth And Arundel',
    'communityCode': '01.E03.1340'},
   'soldDate': '2019-05-06T00:00:00.000Z',
   'resource': 'Property:2381',
   'timestamps': {'listingUpdated': '2019-05-07T14:23:12.000Z'},
   'type': 'Lease',
   'mlsNumber': 'E4424324',
   'permissions': {'displayAddressOnInternet': 'Y', 'displayPublic': 'N'},
   'soldPrice': '2250.00',
   'details': {'numBathrooms': '1',
    'numBedrooms': '2',
    'sqft': '700-1100',
    'style': 'Apartment',
    'yearBuilt': '100+',
    'numBathroomsPlus': None},
   'class': 'ResidentialProperty',
   'map': {'latitude': '43.681158', 'longitude': '-79.352296'},
   'listPrice': '2250.00',
   'lastStatus': 'Lsd',
   'status': 'U',
   'boardId': 2,
   'agents': []},
  {'listDate': '2019-05-01T00:00:00.000Z',
   'images': ['IMG-C4433947_1.jpg',
    'IMG-C4433947_2.jpg',
    'IMG-C4433947_3.jpg',
    'IMG-C4433947_4.jpg',
    'IMG-C4433947_5.jpg',
    'IMG-C4433947_6.jpg',
    'IMG-C4433947_7.jpg',
    'IMG-C4433947_8.jpg'],
   'address': {'area': 'Toronto',
    'zip': 'M2H1K5',
    'country': None,
    'city': 'Toronto',
    'streetNumber': '5',
    'unitNumber': 'Upperfl',
    'streetDirection': '',
    'streetName': 'Deaconwood',
    'district': 'Toronto C15',
    'streetSuffix': 'Rd',
    'neighborhood': 'Bayview Woods-Steeles',
    'state': 'Ontario',
    'majorIntersection': 'Leslie/ Cummer',
    'communityCode': '01.C15.0530'},
   'soldDate': '2019-05-06T00:00:00.000Z',
   'resource': 'Property:2381',
   'timestamps': {'listingUpdated': '2019-05-07T13:58:34.000Z'},
   'type': 'Lease',
   'mlsNumber': 'C4433947',
   'permissions': {'displayAddressOnInternet': 'Y', 'displayPublic': 'N'},
   'soldPrice': '2400.00',
   'details': {'numBathrooms': '1',
    'numBedrooms': '3',
    'sqft': '',
    'style': 'Backsplit 5',
    'yearBuilt': '',
    'numBathroomsPlus': None},
   'class': 'ResidentialProperty',
   'map': {'latitude': '43.795571', 'longitude': '-79.369916'},
   'listPrice': '2300.00',
   'lastStatus': 'Lsd',
   'status': 'U',
   'boardId': 2,
   'agents': []},
  {'listDate': '2019-04-23T00:00:00.000Z',
   'images': ['IMG-W4424200_1.jpg',
    'IMG-W4424200_2.jpg',
    'IMG-W4424200_3.jpg',
    'IMG-W4424200_4.jpg',
    'IMG-W4424200_5.jpg',
    'IMG-W4424200_6.jpg',
    'IMG-W4424200_7.jpg',
    'IMG-W4424200_8.jpg',
    'IMG-W4424200_9.jpg',
    'IMG-W4424200_10.jpg',
    'IMG-W4424200_11.jpg',
    'IMG-W4424200_12.jpg',
    'IMG-W4424200_13.jpg',
    'IMG-W4424200_14.jpg',
    'IMG-W4424200_15.jpg',
    'IMG-W4424200_16.jpg',
    'IMG-W4424200_17.jpg',
    'IMG-W4424200_18.jpg',
    'IMG-W4424200_19.jpg',
    'IMG-W4424200_20.jpg'],
   'address': {'area': 'Peel',
    'zip': 'L5L1H2',
    'country': None,
    'city': 'Mississauga',
    'streetNumber': '3362',
    'unitNumber': '',
    'streetDirection': '',
    'streetName': 'Mainsail',
    'district': 'Mississauga',
    'streetSuffix': 'Cres',
    'neighborhood': 'Erin Mills',
    'state': 'Ontario',
    'majorIntersection': 'The Collegeway/Windjammer Rd',
    'communityCode': '05.03.0080'},
   'soldDate': '2019-05-06T00:00:00.000Z',
   'resource': 'Property:2381',
   'timestamps': {'listingUpdated': '2019-05-07T11:24:17.000Z'},
   'type': 'Lease',
   'mlsNumber': 'W4424200',
   'permissions': {'displayAddressOnInternet': 'Y', 'displayPublic': 'N'},
   'soldPrice': '2600.00',
   'details': {'numBathrooms': '3',
    'numBedrooms': '3',
    'sqft': '',
    'style': '2-Storey',
    'yearBuilt': '',
    'numBathroomsPlus': None},

In [ ]:
len(lease_df)

320770

In [ ]:
subarrays = []
for i in range(0, len(lease_df), 400):
    subarrays.append([lease_df.index[i:i+400]])
if len(subarrays[-1]) > len(lease_df):
    subarrays[-1] = [lease_df.index[subarrays[-1][0], lease_df[len(lease_df)]]]

subarrays

[[Int64Index([  0,   1,   2,   3,   4,   5,   6,   7,   8,   9,
              ...
              390, 391, 392, 393, 394, 395, 396, 397, 398, 399],
             dtype='int64', length=400)],
 [Int64Index([400, 401, 402, 403, 404, 405, 406, 407, 408, 409,
              ...
              790, 791, 792, 793, 794, 795, 796, 797, 798, 799],
             dtype='int64', length=400)],
 [Int64Index([ 800,  801,  802,  803,  804,  805,  806,  807,  808,  809,
              ...
              1190, 1191, 1192, 1193, 1194, 1195, 1196, 1197, 1198, 1199],
             dtype='int64', length=400)],
 [Int64Index([1200, 1201, 1202, 1203, 1204, 1205, 1206, 1207, 1208, 1209,
              ...
              1590, 1591, 1592, 1593, 1594, 1595, 1596, 1597, 1598, 1599],
             dtype='int64', length=400)],
 [Int64Index([1600, 1601, 1602, 1603, 1604, 1605, 1606, 1607, 1608, 1609,
              ...
              1990, 1991, 1992, 1993, 1994, 1995, 1996, 1997, 1998, 1999],
             dtype='int64', length=400)],
 [Int64Index([2000, 2001, 2002, 2003, 2004, 2005, 2006, 2007, 2008, 2009,
              ...
              2390, 2391, 2392, 2393, 2394, 2395, 2396, 2397, 2398, 2399],
             dtype='int64', length=400)],
 [Int64Index([2400, 2401, 2402, 2403, 2404, 2405, 2406, 2407, 2408, 2409,
              ...
              2790, 2791, 2792, 2793, 2794, 2795, 2796, 2797, 2798, 2799],
             dtype='int64', length=400)],
 [Int64Index([2800, 2801, 2802, 2803, 2804, 2805, 2806, 2807, 2808, 2809,
              ...
              3190, 3191, 3192, 3193, 3194, 3195, 3196, 3197, 3198, 3199],
             dtype='int64', length=400)],
 [Int64Index([3200, 3201, 3202, 3203, 3204, 3205, 3206, 3207, 3208, 3209,
              ...
              3590, 3591, 3592, 3593, 3594, 3595, 3596, 3597, 3598, 3599],
             dtype='int64', length=400)],
 [Int64Index([3600, 3601, 3602, 3603, 3604, 3605, 3606, 3607, 3608, 3609,
              ...
              3990, 3991, 3992, 3993, 3994, 3995, 3996, 3997, 3998, 3999],
             dtype='int64', length=400)],
 [Int64Index([4000, 4001, 4002, 4003, 4004, 4005, 4006, 4007, 4008, 4009,
              ...
              4390, 4391, 4392, 4393, 4394, 4395, 4396, 4397, 4398, 4399],
             dtype='int64', length=400)],
 [Int64Index([4400, 4401, 4402, 4403, 4404, 4405, 4406, 4407, 4408, 4409,
              ...
              4790, 4791, 4792, 4793, 4794, 4795, 4796, 4797, 4798, 4799],
             dtype='int64', length=400)],
 [Int64Index([4800, 4801, 4802, 4803, 4804, 4805, 4806, 4807, 4808, 4809,
              ...
              5190, 5191, 5192, 5193, 5194, 5195, 5196, 5197, 5198, 5199],
             dtype='int64', length=400)],
 [Int64Index([5200, 5201, 5202, 5203, 5204, 5205, 5206, 5207, 5208, 5209,
              ...
              5590, 5591, 5592, 5593, 5594, 5595, 5596, 5597, 5598, 5599],
             dtype='int64', length=400)],
 [Int64Index([5600, 5601, 5602, 5603, 5604, 5605, 5606, 5607, 5608, 5609,
              ...
              5990, 5991, 5992, 5993, 5994, 5995, 5996, 5997, 5998, 5999],
             dtype='int64', length=400)],
 [Int64Index([6000, 6001, 6002, 6003, 6004, 6005, 6006, 6007, 6008, 6009,
              ...
              6390, 6391, 6392, 6393, 6394, 6395, 6396, 6397, 6398, 6399],
             dtype='int64', length=400)],
 [Int64Index([6400, 6401, 6402, 6403, 6404, 6405, 6406, 6407, 6408, 6409,
              ...
              6790, 6791, 6792, 6793, 6794, 6795, 6796, 6797, 6798, 6799],
             dtype='int64', length=400)],
 [Int64Index([6800, 6801, 6802, 6803, 6804, 6805, 6806, 6807, 6808, 6809,
              ...
              7190, 7191, 7192, 7193, 7194, 7195, 7196, 7197, 7198, 7199],
             dtype='int64', length=400)],
 [Int64Index([7200, 7201, 7202, 7203, 7204, 7205, 7206, 7207, 7208, 7209,
              ...
              7590, 7591, 7592, 7593, 7594, 7595, 7596, 7597, 7598, 7599],
             dtype='int64', length=400)],
 [Int64Index([7600, 7601, 7602, 7603, 7604, 7605, 7606, 7607, 7608, 7609,
              ...
              7990, 7991, 7992, 7993, 7994, 7995, 7996, 7997, 7998, 7999],
             dtype='int64', length=400)],
 [Int64Index([8000, 8001, 8002, 8003, 8004, 8005, 8006, 8007, 8008, 8009,
              ...
              8390, 8391, 8392, 8393, 8394, 8395, 8396, 8397, 8398, 8399],
             dtype='int64', length=400)],
 [Int64Index([8400, 8401, 8402, 8403, 8404, 8405, 8406, 8407, 8408, 8409,
              ...
              8790, 8791, 8792, 8793, 8794, 8795, 8796, 8797, 8798, 8799],
             dtype='int64', length=400)],
 [Int64Index([8800, 8801, 8802, 8803, 8804, 8805, 8806, 8807, 8808, 8809,
              ...
              9190, 9191, 9192, 9193, 9194, 9195, 9196, 9197, 9198, 9199],
             dtype='int64', length=400)],
 [Int64Index([9200, 9201, 9202, 9203, 9204, 9205, 9206, 9207, 9208, 9209,
              ...
              9590, 9591, 9592, 9593, 9594, 9595, 9596, 9597, 9598, 9599],
             dtype='int64', length=400)],
 [Int64Index([9600, 9601, 9602, 9603, 9604, 9605, 9606, 9607, 9608, 9609,
              ...
              9990, 9991, 9992, 9993, 9994, 9995, 9996, 9997, 9998, 9999],
             dtype='int64', length=400)],
 [Int64Index([10000, 10001, 10002, 10003, 10004, 10005, 10006, 10007, 10008,
              10009,
              ...
              10390, 10391, 10392, 10393, 10394, 10395, 10396, 10397, 10398,
              10399],
             dtype='int64', length=400)],
 [Int64Index([10400, 10401, 10402, 10403, 10404, 10405, 10406, 10407, 10408,
              10409,
              ...
              10790, 10791, 10792, 10793, 10794, 10795, 10796, 10797, 10798,
              10799],
             dtype='int64', length=400)],
 [Int64Index([10800, 10801, 10802, 10803, 10804, 10805, 10806, 10807, 10808,
              10809,
              ...
              11190, 11191, 11192, 11193, 11194, 11195, 11196, 11197, 11198,
              11199],
             dtype='int64', length=400)],
 [Int64Index([11200, 11201, 11202, 11203, 11204, 11205, 11206, 11207, 11208,
              11209,
              ...
              11590, 11591, 11592, 11593, 11594, 11595, 11596, 11597, 11598,
              11599],
             dtype='int64', length=400)],
 [Int64Index([11600, 11601, 11602, 11603, 11604, 11605, 11606, 11607, 11608,
              11609,
              ...
              11990, 11991, 11992, 11993, 11994, 11995, 11996, 11997, 11998,
              11999],
             dtype='int64', length=400)],
 [Int64Index([12000, 12001, 12002, 12003, 12004, 12005, 12006, 12007, 12008,
              12009,
              ...
              12390, 12391, 12392, 12393, 12394, 12395, 12396, 12397, 12398,
              12399],
             dtype='int64', length=400)],
 [Int64Index([12400, 12401, 12402, 12403, 12404, 12405, 12406, 12407, 12408,
              12409,
              ...
              12790, 12791, 12792, 12793, 12794, 12795, 12796, 12797, 12798,
              12799],
             dtype='int64', length=400)],
 [Int64Index([12800, 12801, 12802, 12803, 12804, 12805, 12806, 12807, 12808,
              12809,
              ...
              13190, 13191, 13192, 13193, 13194, 13195, 13196, 13197, 13198,
              13199],
             dtype='int64', length=400)],
 [Int64Index([13200, 13201, 13202, 13203, 13204, 13205, 13206, 13207, 13208,
              13209,
              ...
              13590, 13591, 13592, 13593, 13594, 13595, 13596, 13597, 13598,
              13599],
             dtype='int64', length=400)],
 [Int64Index([13600, 13601, 13602, 13603, 13604, 13605, 13606, 13607, 13608,
              13609,
              ...
              13990, 13991, 13992, 13993, 13994, 13995, 13996, 13997, 13998,
              13999],
             dtype='int64', length=400)],
 [Int64Index([14000, 14001, 14002, 14003, 14004, 14005, 14006, 14007, 14008,
              14009,
              ...
              14390, 14391, 14392, 14393, 14394, 14395, 14396, 14397, 14398,
              14399],
             dtype='int64', length=400)],
 [Int64Index([14400, 14401, 14402, 14403, 14404, 14405, 14406, 14407, 14408,
              14409,
              ...
              14790, 14791, 14792, 14793, 14794, 14795, 14796, 14797, 14798,
              14799],
             dtype='int64', length=400)],
 [Int64Index([14800, 14801, 14802, 14803, 14804, 14805, 14806, 14807, 14808,
              14809,
              ...
              15190, 15191, 15192, 15193, 15194, 15195, 15196, 15197, 15198,
              15199],
             dtype='int64', length=400)],
 [Int64Index([15200, 15201, 15202, 15203, 15204, 15205, 15206, 15207, 15208,
              15209,
              ...
              15590, 15591, 15592, 15593, 15594, 15595, 15596, 15597, 15598,
              15599],
             dtype='int64', length=400)],
 [Int64Index([15600, 15601, 15602, 15603, 15604, 15605, 15606, 15607, 15608,
              15609,
              ...
              15990, 15991, 15992, 15993, 15994, 15995, 15996, 15997, 15998,
              15999],
             dtype='int64', length=400)],
 [Int64Index([16000, 16001, 16002, 16003, 16004, 16005, 16006, 16007, 16008,
              16009,
              ...
              16390, 16391, 16392, 16393, 16394, 16395, 16396, 16397, 16398,
              16399],
             dtype='int64', length=400)],
 [Int64Index([16400, 16401, 16402, 16403, 16404, 16405, 16406, 16407, 16408,
              16409,
              ...
              16790, 16791, 16792, 16793, 16794, 16795, 16796, 16797, 16798,
              16799],
             dtype='int64', length=400)],
 [Int64Index([16800, 16801, 16802, 16803, 16804, 16805, 16806, 16807, 16808,
              16809,
              ...
              17190, 17191, 17192, 17193, 17194, 17195, 17196, 17197, 17198,
              17199],
             dtype='int64', length=400)],
 [Int64Index([17200, 17201, 17202, 17203, 17204, 17205, 17206, 17207, 17208,
              17209,
              ...
              17590, 17591, 17592, 17593, 17594, 17595, 17596, 17597, 17598,
              17599],
             dtype='int64', length=400)],
 [Int64Index([17600, 17601, 17602, 17603, 17604, 17605, 17606, 17607, 17608,
              17609,
              ...
              17990, 17991, 17992, 17993, 17994, 17995, 17996, 17997, 17998,
              17999],
             dtype='int64', length=400)],
 [Int64Index([18000, 18001, 18002, 18003, 18004, 18005, 18006, 18007, 18008,
              18009,
              ...
              18390, 18391, 18392, 18393, 18394, 18395, 18396, 18397, 18398,
              18399],
             dtype='int64', length=400)],
 [Int64Index([18400, 18401, 18402, 18403, 18404, 18405, 18406, 18407, 18408,
              18409,
              ...
              18790, 18791, 18792, 18793, 18794, 18795, 18796, 18797, 18798,
              18799],
             dtype='int64', length=400)],
 [Int64Index([18800, 18801, 18802, 18803, 18804, 18805, 18806, 18807, 18808,
              18809,
              ...
              19190, 19191, 19192, 19193, 19194, 19195, 19196, 19197, 19198,
              19199],
             dtype='int64', length=400)],
 [Int64Index([19200, 19201, 19202, 19203, 19204, 19205, 19206, 19207, 19208,
              19209,
              ...
              19590, 19591, 19592, 19593, 19594, 19595, 19596, 19597, 19598,
              19599],
             dtype='int64', length=400)],
 [Int64Index([19600, 19601, 19602, 19603, 19604, 19605, 19606, 19607, 19608,
              19609,
              ...
              19990, 19991, 19992, 19993, 19994, 19995, 19996, 19997, 19998,
              19999],
             dtype='int64', length=400)],
 [Int64Index([20000, 20001, 20002, 20003, 20004, 20005, 20006, 20007, 20008,
              20009,
              ...
              20390, 20391, 20392, 20393, 20394, 20395, 20396, 20397, 20398,
              20399],
             dtype='int64', length=400)],
 [Int64Index([20400, 20401, 20402, 20403, 20404, 20405, 20406, 20407, 20408,
              20409,
              ...
              20790, 20791, 20792, 20793, 20794, 20795, 20796, 20797, 20798,
              20799],
             dtype='int64', length=400)],
 [Int64Index([20800, 20801, 20802, 20803, 20804, 20805, 20806, 20807, 20808,
              20809,
              ...
              21190, 21191, 21192, 21193, 21194, 21195, 21196, 21197, 21198,
              21199],
             dtype='int64', length=400)],
 [Int64Index([21200, 21201, 21202, 21203, 21204, 21205, 21206, 21207, 21208,
              21209,
              ...
              21590, 21591, 21592, 21593, 21594, 21595, 21596, 21597, 21598,
              21599],
             dtype='int64', length=400)],
 [Int64Index([21600, 21601, 21602, 21603, 21604, 21605, 21606, 21607, 21608,
              21609,
              ...
              21990, 21991, 21992, 21993, 21994, 21995, 21996, 21997, 21998,
              21999],
             dtype='int64', length=400)],
 [Int64Index([22000, 22001, 22002, 22003, 22004, 22005, 22006, 22007, 22008,
              22009,
              ...
              22390, 22391, 22392, 22393, 22394, 22395, 22396, 22397, 22398,
              22399],
             dtype='int64', length=400)],
 [Int64Index([22400, 22401, 22402, 22403, 22404, 22405, 22406, 22407, 22408,
              22409,
              ...
              22790, 22791, 22792, 22793, 22794, 22795, 22796, 22797, 22798,
              22799],
             dtype='int64', length=400)],
 [Int64Index([22800, 22801, 22802, 22803, 22804, 22805, 22806, 22807, 22808,
              22809,
              ...
              23190, 23191, 23192, 23193, 23194, 23195, 23196, 23197, 23198,
              23199],
             dtype='int64', length=400)],
 [Int64Index([23200, 23201, 23202, 23203, 23204, 23205, 23206, 23207, 23208,
              23209,
              ...
              23590, 23591, 23592, 23593, 23594, 23595, 23596, 23597, 23598,
              23599],
             dtype='int64', length=400)],
 [Int64Index([23600, 23601, 23602, 23603, 23604, 23605, 23606, 23607, 23608,
              23609,
              ...
              23990, 23991, 23992, 23993, 23994, 23995, 23996, 23997, 23998,
              23999],
             dtype='int64', length=400)],
 [Int64Index([24000, 24001, 24002, 24003, 24004, 24005, 24006, 24007, 24008,
              24009,
              ...
              24390, 24391, 24392, 24393, 24394, 24395, 24396, 24397, 24398,
              24399],
             dtype='int64', length=400)],
 [Int64Index([24400, 24401, 24402, 24403, 24404, 24405, 24406, 24407, 24408,
              24409,
              ...
              24790, 24791, 24792, 24793, 24794, 24795, 24796, 24797, 24798,
              24799],
             dtype='int64', length=400)],
 [Int64Index([24800, 24801, 24802, 24803, 24804, 24805, 24806, 24807, 24808,
              24809,
              ...
              25190, 25191, 25192, 25193, 25194, 25195, 25196, 25197, 25198,
              25199],
             dtype='int64', length=400)],
 [Int64Index([25200, 25201, 25202, 25203, 25204, 25205, 25206, 25207, 25208,
              25209,
              ...
              25590, 25591, 25592, 25593, 25594, 25595, 25596, 25597, 25598,
              25599],
             dtype='int64', length=400)],
 [Int64Index([25600, 25601, 25602, 25603, 25604, 25605, 25606, 25607, 25608,
              25609,
              ...
              25990, 25991, 25992, 25993, 25994, 25995, 25996, 25997, 25998,
              25999],
             dtype='int64', length=400)],
 [Int64Index([26000, 26001, 26002, 26003, 26004, 26005, 26006, 26007, 26008,
              26009,
              ...
              26390, 26391, 26392, 26393, 26394, 26395, 26396, 26397, 26398,
              26399],
             dtype='int64', length=400)],
 [Int64Index([26400, 26401, 26402, 26403, 26404, 26405, 26406, 26407, 26408,
              26409,
              ...
              26790, 26791, 26792, 26793, 26794, 26795, 26796, 26797, 26798,
              26799],
             dtype='int64', length=400)],
 [Int64Index([26800, 26801, 26802, 26803, 26804, 26805, 26806, 26807, 26808,
              26809,
              ...
              27190, 27191, 27192, 27193, 27194, 27195, 27196, 27197, 27198,
              27199],
             dtype='int64', length=400)],
 [Int64Index([27200, 27201, 27202, 27203, 27204, 27205, 27206, 27207, 27208,
              27209,
              ...
              27590, 27591, 27592, 27593, 27594, 27595, 27596, 27597, 27598,
              27599],
             dtype='int64', length=400)],
 [Int64Index([27600, 27601, 27602, 27603, 27604, 27605, 27606, 27607, 27608,
              27609,
              ...
              27990, 27991, 27992, 27993, 27994, 27995, 27996, 27997, 27998,
              27999],
             dtype='int64', length=400)],
 [Int64Index([28000, 28001, 28002, 28003, 28004, 28005, 28006, 28007, 28008,
              28009,
              ...
              28390, 28391, 28392, 28393, 28394, 28395, 28396, 28397, 28398,
              28399],
             dtype='int64', length=400)],
 [Int64Index([28400, 28401, 28402, 28403, 28404, 28405, 28406, 28407, 28408,
              28409,
              ...
              28790, 28791, 28792, 28793, 28794, 28795, 28796, 28797, 28798,
              28799],
             dtype='int64', length=400)],
 [Int64Index([28800, 28801, 28802, 28803, 28804, 28805, 28806, 28807, 28808,
              28809,
              ...
              29190, 29191, 29192, 29193, 29194, 29195, 29196, 29197, 29198,
              29199],
             dtype='int64', length=400)],
 [Int64Index([29200, 29201, 29202, 29203, 29204, 29205, 29206, 29207, 29208,
              29209,
              ...
              29590, 29591, 29592, 29593, 29594, 29595, 29596, 29597, 29598,
              29599],
             dtype='int64', length=400)],
 [Int64Index([29600, 29601, 29602, 29603, 29604, 29605, 29606, 29607, 29608,
              29609,
              ...
              29990, 29991, 29992, 29993, 29994, 29995, 29996, 29997, 29998,
              29999],
             dtype='int64', length=400)],
 [Int64Index([30000, 30001, 30002, 30003, 30004, 30005, 30006, 30007, 30008,
              30009,
              ...
              30390, 30391, 30392, 30393, 30394, 30395, 30396, 30397, 30398,
              30399],
             dtype='int64', length=400)],
 [Int64Index([30400, 30401, 30402, 30403, 30404, 30405, 30406, 30407, 30408,
              30409,
              ...
              30790, 30791, 30792, 30793, 30794, 30795, 30796, 30797, 30798,
              30799],
             dtype='int64', length=400)],
 [Int64Index([30800, 30801, 30802, 30803, 30804, 30805, 30806, 30807, 30808,
              30809,
              ...
              31190, 31191, 31192, 31193, 31194, 31195, 31196, 31197, 31198,
              31199],
             dtype='int64', length=400)],
 [Int64Index([31200, 31201, 31202, 31203, 31204, 31205, 31206, 31207, 31208,
              31209,
              ...
              31590, 31591, 31592, 31593, 31594, 31595, 31596, 31597, 31598,
              31599],
             dtype='int64', length=400)],
 [Int64Index([31600, 31601, 31602, 31603, 31604, 31605, 31606, 31607, 31608,
              31609,
              ...
              31990, 31991, 31992, 31993, 31994, 31995, 31996, 31997, 31998,
              31999],
             dtype='int64', length=400)],
 [Int64Index([32000, 32001, 32002, 32003, 32004, 32005, 32006, 32007, 32008,
              32009,
              ...
              32390, 32391, 32392, 32393, 32394, 32395, 32396, 32397, 32398,
              32399],
             dtype='int64', length=400)],
 [Int64Index([32400, 32401, 32402, 32403, 32404, 32405, 32406, 32407, 32408,
              32409,
              ...
              32790, 32791, 32792, 32793, 32794, 32795, 32796, 32797, 32798,
              32799],
             dtype='int64', length=400)],
 [Int64Index([32800, 32801, 32802, 32803, 32804, 32805, 32806, 32807, 32808,
              32809,
              ...

In [ ]:
import asyncio

async def count():
    data = [1, 2, 3, 4, 5]
    for x in data:
        print(x)
    print("sleeping")
    await asyncio.sleep(1)
    print("done sleeping")
    print("Two")

    return 1

async def count2(x):
    print("three")
    print(x+1)

    


async def main():
    await asyncio.gather(count(), count2())


final = await main()

1
2
3
4
5
sleeping
three

TypeError: unsupported operand type(s) for +: 'coroutine' and 'int'

done sleeping
Two

In [ ]:
import asyncio

async def process_x(x):
    print(f"Processing {x}")
    await asyncio.sleep(1)
    print(f"Finished processing {x}")
    return x * 2

async def process_y(x):
    print(f"Processing y on {x}")
    return x * 3

async def main():
    data = [1, 2, 3, 4, 5,6,7,8,9,10,11,12,13,14,15,16,17,18,19,20]
    for x in data:
        # Create a task for process_x
        task_x = asyncio.create_task(process_x(x))

        # Run process_y immediately while process_x is sleeping
        result_y = process_y(x)
        print(f"Results for y on {x}: {result_y}")

        # Wait for process_x to complete
        result_x = await task_x
        print(f"Results for x: {result_x}")

# Run the main function using the asyncio event loop
await main()

Processing y on 1
Results for y on 1: 3
Processing 1
Finished processing 1
Results for x: 2
Processing y on 2
Results for y on 2: 6
Processing 2
Finished processing 2
Results for x: 4
Processing y on 3
Results for y on 3: 9
Processing 3
Finished processing 3
Results for x: 6
Processing y on 4
Results for y on 4: 12
Processing 4
Finished processing 4
Results for x: 8
Processing y on 5
Results for y on 5: 15
Processing 5
Finished processing 5
Results for x: 10
Processing y on 6
Results for y on 6: 18
Processing 6
Finished processing 6
Results for x: 12
Processing y on 7
Results for y on 7: 21
Processing 7
Finished processing 7
Results for x: 14
Processing y on 8
Results for y on 8: 24
Processing 8
Finished processing 8
Results for x: 16
Processing y on 9
Results for y on 9: 27
Processing 9
Finished processing 9
Results for x: 18
Processing y on 10
Results for y on 10: 30
Processing 10
Finished processing 10
Results for x: 20
Processing y on 11
Results for y on 11: 33
Processing 11
Finished processing 11
Results for x: 22
Processing y on 12
Results for y on 12: 36
Processing 12
Finished processing 12
Results for x: 24
Processing y on 13
Results for y on 13: 39
Processing 13
Finished processing 13
Results for x: 26
Processing y on 14
Results for y on 14: 42
Processing 14
Finished processing 14
Results for x: 28
Processing y on 15
Results for y on 15: 45
Processing 15
Finished processing 15
Results for x: 30
Processing y on 16
Results for y on 16: 48
Processing 16
Finished processing 16
Results for x: 32
Processing y on 17
Results for y on 17: 51
Processing 17
Finished processing 17
Results for x: 34
Processing y on 18
Results for y on 18: 54
Processing 18
Finished processing 18
Results for x: 36
Processing y on 19
Results for y on 19: 57
Processing 19
Finished processing 19
Results for x: 38
Processing y on 20
Results for y on 20: 60
Processing 20
Finished processing 20
Results for x: 40

In [ ]:
import asyncio

async def process_x(x):
    print(f"grabbed {x}")
    print("sleeping")
    await asyncio.sleep(1)
    print("done sleeping")
    print(f"returning {x*2}")
    return x * 2

async def process_y(x):
    print(f"grabbed x returning y on {x}")
    return -x

async def main():
    data = [1, 2, 3, 4, 5]
    for x in data:
        # Create a task for process_x
        task_x = asyncio.create_task(process_x(x))
        
        # Run process_y immediately while process_x is sleeping

        result_x = await task_x

        result_y = process_y(result_x)
        print(f"Results for y on {x}: {result_y}")

        # Wait for process_x to complete
        #result_x = await task_x
        #print(f"Results for x: {result_x}")

# Run the main function using the asyncio event loop
await main()

grabbed 1
sleeping
done sleeping
returning 2
Results for y on 1: <coroutine object process_y at 0x000001B482B1A240>
grabbed 2
sleeping
done sleeping
returning 4
Results for y on 2: <coroutine object process_y at 0x000001B482B1A340>
grabbed 3
sleeping

C:\Users\Jackson\AppData\Local\Temp\ipykernel_36932\3058223667.py:25: RuntimeWarning: coroutine 'process_y' was never awaited
  result_y = process_y(result_x)
RuntimeWarning: Enable tracemalloc to get the object allocation traceback

done sleeping
returning 6
Results for y on 3: <coroutine object process_y at 0x000001B482B1A2C0>
grabbed 4
sleeping
done sleeping
returning 8
Results for y on 4: <coroutine object process_y at 0x000001B482B1A240>
grabbed 5
sleeping
done sleeping
returning 10
Results for y on 5: <coroutine object process_y at 0x000001B482B1A340>

C:\Users\Jackson\AppData\Local\Temp\ipykernel_36932\3058223667.py:33: RuntimeWarning: coroutine 'process_y' was never awaited
  await main()
RuntimeWarning: Enable tracemalloc to get the object allocation traceback

In [ ]:
import asyncio

async def task1():
    for x in [1,2,3,4,5]:
        print("Task 1 started")
        print(x)
        print("sleeping")
        await asyncio.sleep(3)
        print("done sleeping")
    result = "Task 1 completed"
    return result

async def task2():
    print("Task 2 started")
    task1_result = await task1()
    print("Task 2 received task1 result: ", task1_result)
    for i in range(5):
        print("Task 2 running")
        await asyncio.sleep(1)
    print("Task 2 completed")

async def main():
    # Run both tasks concurrently
    task2_coro = asyncio.create_task(task2())

    # Wait for task2 to complete
    await task2_coro

# Run the main function using the asyncio event loop
await main()

In [75]:
subarrays = []
for i in range(0, len(lease_df), 400):
    subarrays.append(lease_df.index[i:i+400])
if len(subarrays[-1]) > len(lease_df):
    subarrays[-1] = [lease_df.index[subarrays[-1][0], lease_df[len(lease_df)]]]

subarrays

[Int64Index([  0,   1,   2,   3,   4,   5,   6,   7,   8,   9,
             ...
             390, 391, 392, 393, 394, 395, 396, 397, 398, 399],
            dtype='int64', length=400),
 Int64Index([400, 401, 402, 403, 404, 405, 406, 407, 408, 409,
             ...
             790, 791, 792, 793, 794, 795, 796, 797, 798, 799],
            dtype='int64', length=400),
 Int64Index([ 800,  801,  802,  803,  804,  805,  806,  807,  808,  809,
             ...
             1190, 1191, 1192, 1193, 1194, 1195, 1196, 1197, 1198, 1199],
            dtype='int64', length=400),
 Int64Index([1200, 1201, 1202, 1203, 1204, 1205, 1206, 1207, 1208, 1209,
             ...
             1590, 1591, 1592, 1593, 1594, 1595, 1596, 1597, 1598, 1599],
            dtype='int64', length=400),
 Int64Index([1600, 1601, 1602, 1603, 1604, 1605, 1606, 1607, 1608, 1609,
             ...
             1990, 1991, 1992, 1993, 1994, 1995, 1996, 1997, 1998, 1999],
            dtype='int64', length=400),
 Int64Index([2000, 2001, 2002, 2003, 2004, 2005, 2006, 2007, 2008, 2009,
             ...
             2390, 2391, 2392, 2393, 2394, 2395, 2396, 2397, 2398, 2399],
            dtype='int64', length=400),
 Int64Index([2400, 2401, 2402, 2403, 2404, 2405, 2406, 2407, 2408, 2409,
             ...
             2790, 2791, 2792, 2793, 2794, 2795, 2796, 2797, 2798, 2799],
            dtype='int64', length=400),
 Int64Index([2800, 2801, 2802, 2803, 2804, 2805, 2806, 2807, 2808, 2809,
             ...
             3190, 3191, 3192, 3193, 3194, 3195, 3196, 3197, 3198, 3199],
            dtype='int64', length=400),
 Int64Index([3200, 3201, 3202, 3203, 3204, 3205, 3206, 3207, 3208, 3209,
             ...
             3590, 3591, 3592, 3593, 3594, 3595, 3596, 3597, 3598, 3599],
            dtype='int64', length=400),
 Int64Index([3600, 3601, 3602, 3603, 3604, 3605, 3606, 3607, 3608, 3609,
             ...
             3990, 3991, 3992, 3993, 3994, 3995, 3996, 3997, 3998, 3999],
            dtype='int64', length=400),
 Int64Index([4000, 4001, 4002, 4003, 4004, 4005, 4006, 4007, 4008, 4009,
             ...
             4390, 4391, 4392, 4393, 4394, 4395, 4396, 4397, 4398, 4399],
            dtype='int64', length=400),
 Int64Index([4400, 4401, 4402, 4403, 4404, 4405, 4406, 4407, 4408, 4409,
             ...
             4790, 4791, 4792, 4793, 4794, 4795, 4796, 4797, 4798, 4799],
            dtype='int64', length=400),
 Int64Index([4800, 4801, 4802, 4803, 4804, 4805, 4806, 4807, 4808, 4809,
             ...
             5190, 5191, 5192, 5193, 5194, 5195, 5196, 5197, 5198, 5199],
            dtype='int64', length=400),
 Int64Index([5200, 5201, 5202, 5203, 5204, 5205, 5206, 5207, 5208, 5209,
             ...
             5590, 5591, 5592, 5593, 5594, 5595, 5596, 5597, 5598, 5599],
            dtype='int64', length=400),
 Int64Index([5600, 5601, 5602, 5603, 5604, 5605, 5606, 5607, 5608, 5609,
             ...
             5990, 5991, 5992, 5993, 5994, 5995, 5996, 5997, 5998, 5999],
            dtype='int64', length=400),
 Int64Index([6000, 6001, 6002, 6003, 6004, 6005, 6006, 6007, 6008, 6009,
             ...
             6390, 6391, 6392, 6393, 6394, 6395, 6396, 6397, 6398, 6399],
            dtype='int64', length=400),
 Int64Index([6400, 6401, 6402, 6403, 6404, 6405, 6406, 6407, 6408, 6409,
             ...
             6790, 6791, 6792, 6793, 6794, 6795, 6796, 6797, 6798, 6799],
            dtype='int64', length=400),
 Int64Index([6800, 6801, 6802, 6803, 6804, 6805, 6806, 6807, 6808, 6809,
             ...
             7190, 7191, 7192, 7193, 7194, 7195, 7196, 7197, 7198, 7199],
            dtype='int64', length=400),
 Int64Index([7200, 7201, 7202, 7203, 7204, 7205, 7206, 7207, 7208, 7209,
             ...
             7590, 7591, 7592, 7593, 7594, 7595, 7596, 7597, 7598, 7599],
            dtype='int64', length=400),
 Int64Index([7600, 7601, 7602, 7603, 7604, 7605, 7606, 7607, 7608, 7609,
             ...
             7990, 7991, 7992, 7993, 7994, 7995, 7996, 7997, 7998, 7999],
            dtype='int64', length=400),
 Int64Index([8000, 8001, 8002, 8003, 8004, 8005, 8006, 8007, 8008, 8009,
             ...
             8390, 8391, 8392, 8393, 8394, 8395, 8396, 8397, 8398, 8399],
            dtype='int64', length=400),
 Int64Index([8400, 8401, 8402, 8403, 8404, 8405, 8406, 8407, 8408, 8409,
             ...
             8790, 8791, 8792, 8793, 8794, 8795, 8796, 8797, 8798, 8799],
            dtype='int64', length=400),
 Int64Index([8800, 8801, 8802, 8803, 8804, 8805, 8806, 8807, 8808, 8809,
             ...
             9190, 9191, 9192, 9193, 9194, 9195, 9196, 9197, 9198, 9199],
            dtype='int64', length=400),
 Int64Index([9200, 9201, 9202, 9203, 9204, 9205, 9206, 9207, 9208, 9209,
             ...
             9590, 9591, 9592, 9593, 9594, 9595, 9596, 9597, 9598, 9599],
            dtype='int64', length=400),
 Int64Index([9600, 9601, 9602, 9603, 9604, 9605, 9606, 9607, 9608, 9609,
             ...
             9990, 9991, 9992, 9993, 9994, 9995, 9996, 9997, 9998, 9999],
            dtype='int64', length=400),
 Int64Index([10000, 10001, 10002, 10003, 10004, 10005, 10006, 10007, 10008,
             10009,
             ...
             10390, 10391, 10392, 10393, 10394, 10395, 10396, 10397, 10398,
             10399],
            dtype='int64', length=400),
 Int64Index([10400, 10401, 10402, 10403, 10404, 10405, 10406, 10407, 10408,
             10409,
             ...
             10790, 10791, 10792, 10793, 10794, 10795, 10796, 10797, 10798,
             10799],
            dtype='int64', length=400),
 Int64Index([10800, 10801, 10802, 10803, 10804, 10805, 10806, 10807, 10808,
             10809,
             ...
             11190, 11191, 11192, 11193, 11194, 11195, 11196, 11197, 11198,
             11199],
            dtype='int64', length=400),
 Int64Index([11200, 11201, 11202, 11203, 11204, 11205, 11206, 11207, 11208,
             11209,
             ...
             11590, 11591, 11592, 11593, 11594, 11595, 11596, 11597, 11598,
             11599],
            dtype='int64', length=400),
 Int64Index([11600, 11601, 11602, 11603, 11604, 11605, 11606, 11607, 11608,
             11609,
             ...
             11990, 11991, 11992, 11993, 11994, 11995, 11996, 11997, 11998,
             11999],
            dtype='int64', length=400),
 Int64Index([12000, 12001, 12002, 12003, 12004, 12005, 12006, 12007, 12008,
             12009,
             ...
             12390, 12391, 12392, 12393, 12394, 12395, 12396, 12397, 12398,
             12399],
            dtype='int64', length=400),
 Int64Index([12400, 12401, 12402, 12403, 12404, 12405, 12406, 12407, 12408,
             12409,
             ...
             12790, 12791, 12792, 12793, 12794, 12795, 12796, 12797, 12798,
             12799],
            dtype='int64', length=400),
 Int64Index([12800, 12801, 12802, 12803, 12804, 12805, 12806, 12807, 12808,
             12809,
             ...
             13190, 13191, 13192, 13193, 13194, 13195, 13196, 13197, 13198,
             13199],
            dtype='int64', length=400),
 Int64Index([13200, 13201, 13202, 13203, 13204, 13205, 13206, 13207, 13208,
             13209,
             ...
             13590, 13591, 13592, 13593, 13594, 13595, 13596, 13597, 13598,
             13599],
            dtype='int64', length=400),
 Int64Index([13600, 13601, 13602, 13603, 13604, 13605, 13606, 13607, 13608,
             13609,
             ...
             13990, 13991, 13992, 13993, 13994, 13995, 13996, 13997, 13998,
             13999],
            dtype='int64', length=400),
 Int64Index([14000, 14001, 14002, 14003, 14004, 14005, 14006, 14007, 14008,
             14009,
             ...
             14390, 14391, 14392, 14393, 14394, 14395, 14396, 14397, 14398,
             14399],
            dtype='int64', length=400),
 Int64Index([14400, 14401, 14402, 14403, 14404, 14405, 14406, 14407, 14408,
             14409,
             ...
             14790, 14791, 14792, 14793, 14794, 14795, 14796, 14797, 14798,
             14799],
            dtype='int64', length=400),
 Int64Index([14800, 14801, 14802, 14803, 14804, 14805, 14806, 14807, 14808,
             14809,
             ...
             15190, 15191, 15192, 15193, 15194, 15195, 15196, 15197, 15198,
             15199],
            dtype='int64', length=400),
 Int64Index([15200, 15201, 15202, 15203, 15204, 15205, 15206, 15207, 15208,
             15209,
             ...
             15590, 15591, 15592, 15593, 15594, 15595, 15596, 15597, 15598,
             15599],
            dtype='int64', length=400),
 Int64Index([15600, 15601, 15602, 15603, 15604, 15605, 15606, 15607, 15608,
             15609,
             ...
             15990, 15991, 15992, 15993, 15994, 15995, 15996, 15997, 15998,
             15999],
            dtype='int64', length=400),
 Int64Index([16000, 16001, 16002, 16003, 16004, 16005, 16006, 16007, 16008,
             16009,
             ...
             16390, 16391, 16392, 16393, 16394, 16395, 16396, 16397, 16398,
             16399],
            dtype='int64', length=400),
 Int64Index([16400, 16401, 16402, 16403, 16404, 16405, 16406, 16407, 16408,
             16409,
             ...
             16790, 16791, 16792, 16793, 16794, 16795, 16796, 16797, 16798,
             16799],
            dtype='int64', length=400),
 Int64Index([16800, 16801, 16802, 16803, 16804, 16805, 16806, 16807, 16808,
             16809,
             ...
             17190, 17191, 17192, 17193, 17194, 17195, 17196, 17197, 17198,
             17199],
            dtype='int64', length=400),
 Int64Index([17200, 17201, 17202, 17203, 17204, 17205, 17206, 17207, 17208,
             17209,
             ...
             17590, 17591, 17592, 17593, 17594, 17595, 17596, 17597, 17598,
             17599],
            dtype='int64', length=400),
 Int64Index([17600, 17601, 17602, 17603, 17604, 17605, 17606, 17607, 17608,
             17609,
             ...
             17990, 17991, 17992, 17993, 17994, 17995, 17996, 17997, 17998,
             17999],
            dtype='int64', length=400),
 Int64Index([18000, 18001, 18002, 18003, 18004, 18005, 18006, 18007, 18008,
             18009,
             ...
             18390, 18391, 18392, 18393, 18394, 18395, 18396, 18397, 18398,
             18399],
            dtype='int64', length=400),
 Int64Index([18400, 18401, 18402, 18403, 18404, 18405, 18406, 18407, 18408,
             18409,
             ...
             18790, 18791, 18792, 18793, 18794, 18795, 18796, 18797, 18798,
             18799],
            dtype='int64', length=400),
 Int64Index([18800, 18801, 18802, 18803, 18804, 18805, 18806, 18807, 18808,
             18809,
             ...
             19190, 19191, 19192, 19193, 19194, 19195, 19196, 19197, 19198,
             19199],
            dtype='int64', length=400),
 Int64Index([19200, 19201, 19202, 19203, 19204, 19205, 19206, 19207, 19208,
             19209,
             ...
             19590, 19591, 19592, 19593, 19594, 19595, 19596, 19597, 19598,
             19599],
            dtype='int64', length=400),
 Int64Index([19600, 19601, 19602, 19603, 19604, 19605, 19606, 19607, 19608,
             19609,
             ...
             19990, 19991, 19992, 19993, 19994, 19995, 19996, 19997, 19998,
             19999],
            dtype='int64', length=400),
 Int64Index([20000, 20001, 20002, 20003, 20004, 20005, 20006, 20007, 20008,
             20009,
             ...
             20390, 20391, 20392, 20393, 20394, 20395, 20396, 20397, 20398,
             20399],
            dtype='int64', length=400),
 Int64Index([20400, 20401, 20402, 20403, 20404, 20405, 20406, 20407, 20408,
             20409,
             ...
             20790, 20791, 20792, 20793, 20794, 20795, 20796, 20797, 20798,
             20799],
            dtype='int64', length=400),
 Int64Index([20800, 20801, 20802, 20803, 20804, 20805, 20806, 20807, 20808,
             20809,
             ...
             21190, 21191, 21192, 21193, 21194, 21195, 21196, 21197, 21198,
             21199],
            dtype='int64', length=400),
 Int64Index([21200, 21201, 21202, 21203, 21204, 21205, 21206, 21207, 21208,
             21209,
             ...
             21590, 21591, 21592, 21593, 21594, 21595, 21596, 21597, 21598,
             21599],
            dtype='int64', length=400),
 Int64Index([21600, 21601, 21602, 21603, 21604, 21605, 21606, 21607, 21608,
             21609,
             ...
             21990, 21991, 21992, 21993, 21994, 21995, 21996, 21997, 21998,
             21999],
            dtype='int64', length=400),
 Int64Index([22000, 22001, 22002, 22003, 22004, 22005, 22006, 22007, 22008,
             22009,
             ...
             22390, 22391, 22392, 22393, 22394, 22395, 22396, 22397, 22398,
             22399],
            dtype='int64', length=400),
 Int64Index([22400, 22401, 22402, 22403, 22404, 22405, 22406, 22407, 22408,
             22409,
             ...
             22790, 22791, 22792, 22793, 22794, 22795, 22796, 22797, 22798,
             22799],
            dtype='int64', length=400),
 Int64Index([22800, 22801, 22802, 22803, 22804, 22805, 22806, 22807, 22808,
             22809,
             ...
             23190, 23191, 23192, 23193, 23194, 23195, 23196, 23197, 23198,
             23199],
            dtype='int64', length=400),
 Int64Index([23200, 23201, 23202, 23203, 23204, 23205, 23206, 23207, 23208,
             23209,
             ...
             23590, 23591, 23592, 23593, 23594, 23595, 23596, 23597, 23598,
             23599],
            dtype='int64', length=400),
 Int64Index([23600, 23601, 23602, 23603, 23604, 23605, 23606, 23607, 23608,
             23609,
             ...
             23990, 23991, 23992, 23993, 23994, 23995, 23996, 23997, 23998,
             23999],
            dtype='int64', length=400),
 Int64Index([24000, 24001, 24002, 24003, 24004, 24005, 24006, 24007, 24008,
             24009,
             ...
             24390, 24391, 24392, 24393, 24394, 24395, 24396, 24397, 24398,
             24399],
            dtype='int64', length=400),
 Int64Index([24400, 24401, 24402, 24403, 24404, 24405, 24406, 24407, 24408,
             24409,
             ...
             24790, 24791, 24792, 24793, 24794, 24795, 24796, 24797, 24798,
             24799],
            dtype='int64', length=400),
 Int64Index([24800, 24801, 24802, 24803, 24804, 24805, 24806, 24807, 24808,
             24809,
             ...
             25190, 25191, 25192, 25193, 25194, 25195, 25196, 25197, 25198,
             25199],
            dtype='int64', length=400),
 Int64Index([25200, 25201, 25202, 25203, 25204, 25205, 25206, 25207, 25208,
             25209,
             ...
             25590, 25591, 25592, 25593, 25594, 25595, 25596, 25597, 25598,
             25599],
            dtype='int64', length=400),
 Int64Index([25600, 25601, 25602, 25603, 25604, 25605, 25606, 25607, 25608,
             25609,
             ...
             25990, 25991, 25992, 25993, 25994, 25995, 25996, 25997, 25998,
             25999],
            dtype='int64', length=400),
 Int64Index([26000, 26001, 26002, 26003, 26004, 26005, 26006, 26007, 26008,
             26009,
             ...
             26390, 26391, 26392, 26393, 26394, 26395, 26396, 26397, 26398,
             26399],
            dtype='int64', length=400),
 Int64Index([26400, 26401, 26402, 26403, 26404, 26405, 26406, 26407, 26408,
             26409,
             ...
             26790, 26791, 26792, 26793, 26794, 26795, 26796, 26797, 26798,
             26799],
            dtype='int64', length=400),
 Int64Index([26800, 26801, 26802, 26803, 26804, 26805, 26806, 26807, 26808,
             26809,
             ...
             27190, 27191, 27192, 27193, 27194, 27195, 27196, 27197, 27198,
             27199],
            dtype='int64', length=400),
 Int64Index([27200, 27201, 27202, 27203, 27204, 27205, 27206, 27207, 27208,
             27209,
             ...
             27590, 27591, 27592, 27593, 27594, 27595, 27596, 27597, 27598,
             27599],
            dtype='int64', length=400),
 Int64Index([27600, 27601, 27602, 27603, 27604, 27605, 27606, 27607, 27608,
             27609,
             ...
             27990, 27991, 27992, 27993, 27994, 27995, 27996, 27997, 27998,
             27999],
            dtype='int64', length=400),
 Int64Index([28000, 28001, 28002, 28003, 28004, 28005, 28006, 28007, 28008,
             28009,
             ...
             28390, 28391, 28392, 28393, 28394, 28395, 28396, 28397, 28398,
             28399],
            dtype='int64', length=400),
 Int64Index([28400, 28401, 28402, 28403, 28404, 28405, 28406, 28407, 28408,
             28409,
             ...
             28790, 28791, 28792, 28793, 28794, 28795, 28796, 28797, 28798,
             28799],
            dtype='int64', length=400),
 Int64Index([28800, 28801, 28802, 28803, 28804, 28805, 28806, 28807, 28808,
             28809,
             ...
             29190, 29191, 29192, 29193, 29194, 29195, 29196, 29197, 29198,
             29199],
            dtype='int64', length=400),
 Int64Index([29200, 29201, 29202, 29203, 29204, 29205, 29206, 29207, 29208,
             29209,
             ...
             29590, 29591, 29592, 29593, 29594, 29595, 29596, 29597, 29598,
             29599],
            dtype='int64', length=400),
 Int64Index([29600, 29601, 29602, 29603, 29604, 29605, 29606, 29607, 29608,
             29609,
             ...
             29990, 29991, 29992, 29993, 29994, 29995, 29996, 29997, 29998,
             29999],
            dtype='int64', length=400),
 Int64Index([30000, 30001, 30002, 30003, 30004, 30005, 30006, 30007, 30008,
             30009,
             ...
             30390, 30391, 30392, 30393, 30394, 30395, 30396, 30397, 30398,
             30399],
            dtype='int64', length=400),
 Int64Index([30400, 30401, 30402, 30403, 30404, 30405, 30406, 30407, 30408,
             30409,
             ...
             30790, 30791, 30792, 30793, 30794, 30795, 30796, 30797, 30798,
             30799],
            dtype='int64', length=400),
 Int64Index([30800, 30801, 30802, 30803, 30804, 30805, 30806, 30807, 30808,
             30809,
             ...
             31190, 31191, 31192, 31193, 31194, 31195, 31196, 31197, 31198,
             31199],
            dtype='int64', length=400),
 Int64Index([31200, 31201, 31202, 31203, 31204, 31205, 31206, 31207, 31208,
             31209,
             ...
             31590, 31591, 31592, 31593, 31594, 31595, 31596, 31597, 31598,
             31599],
            dtype='int64', length=400),
 Int64Index([31600, 31601, 31602, 31603, 31604, 31605, 31606, 31607, 31608,
             31609,
             ...
             31990, 31991, 31992, 31993, 31994, 31995, 31996, 31997, 31998,
             31999],
            dtype='int64', length=400),
 Int64Index([32000, 32001, 32002, 32003, 32004, 32005, 32006, 32007, 32008,
             32009,
             ...
             32390, 32391, 32392, 32393, 32394, 32395, 32396, 32397, 32398,
             32399],
            dtype='int64', length=400),
 Int64Index([32400, 32401, 32402, 32403, 32404, 32405, 32406, 32407, 32408,
             32409,
             ...
             32790, 32791, 32792, 32793, 32794, 32795, 32796, 32797, 32798,
             32799],
            dtype='int64', length=400),
 Int64Index([32800, 32801, 32802, 32803, 32804, 32805, 32806, 32807, 32808,
             32809,
             ...
             33190, 33191, 33192, 33193, 33194, 33195, 33196, 33197, 33198,
             33199],
            dtype='int64', length=400),
 Int64Index([33200, 33201, 33202, 33203, 33204, 33205, 33206, 33207, 33208,
             33209,
             ...
             33590, 33591, 33592, 33593, 33594, 33595, 33596, 33597, 33598,
             33599],
            dtype='int64', length=400),
 Int64Index([33600, 33601, 33602, 33603, 33604, 33605, 33606, 33607, 33608,
             33609,
             ...
             33990, 33991, 33992, 33993, 33994, 33995, 33996, 33997, 33998,

In [76]:
len(subarrays)

802

In [77]:
subarrays[-1][0]

320401

In [78]:
import asyncio
import queue

async def request_comparable_listings(q):
    print("Task 1 started")
    for lst in subarrays:
        #print(f"putting in {i}")
        await q.put(lst)
        print("sleeping")
        await asyncio.sleep(1)
        print("done sleeping")
    print("Task 1 completed")

# async def task2(q):
#     print("Task 2 started")
#     while True:
#         try:
#             value = q.get()
#             print("Task 2 received value:", value)
#         except queue.Empty():
#             print("Task 2 waiting for value...")
#             await asyncio.sleep(1)
#             continue
#         if value is None:
#             print("Task 2 completed")
#             break

async def get_average_price(q):
    print("Task 2 started")
    while True:
        print("Task 2 waiting for item...")
        value = await q.get()
        if value is None:
            print("Task 2 completed")
            break
        else:
            print("Task 2 received value:", value)
            print(value//2)


async def main():
    q = asyncio.Queue()
    # Run both tasks concurrently
    task1_coro = asyncio.create_task(request_comparable_listings(q))
    task2_coro = asyncio.create_task(get_average_price(q))

    # Wait for task1 to complete
    await task1_coro

    # Signal task2 to complete
    await q.put(None)
    await task2_coro

# Start the event loop and run the main coroutine
await main()

Task 1 started
sleeping
Task 2 started
Task 2 waiting for item...
Task 2 received value: Int64Index([  0,   1,   2,   3,   4,   5,   6,   7,   8,   9,
            ...
            390, 391, 392, 393, 394, 395, 396, 397, 398, 399],
           dtype='int64', length=400)
Int64Index([  0,   0,   1,   1,   2,   2,   3,   3,   4,   4,
            ...
            195, 195, 196, 196, 197, 197, 198, 198, 199, 199],
           dtype='int64', length=400)
Task 2 waiting for item...
done sleeping
sleeping
Task 2 received value: Int64Index([400, 401, 402, 403, 404, 405, 406, 407, 408, 409,
            ...
            790, 791, 792, 793, 794, 795, 796, 797, 798, 799],
           dtype='int64', length=400)
Int64Index([200, 200, 201, 201, 202, 202, 203, 203, 204, 204,
            ...
            395, 395, 396, 396, 397, 397, 398, 398, 399, 399],
           dtype='int64', length=400)
Task 2 waiting for item...
done sleeping
sleeping
Task 2 received value: Int64Index([ 800,  801,  802,  803,  804,  805,  806,  807,  808,  809,
            ...
            1190, 1191, 1192, 1193, 1194, 1195, 1196, 1197, 1198, 1199],
           dtype='int64', length=400)
Int64Index([400, 400, 401, 401, 402, 402, 403, 403, 404, 404,
            ...
            595, 595, 596, 596, 597, 597, 598, 598, 599, 599],
           dtype='int64', length=400)
Task 2 waiting for item...
done sleeping
sleeping
Task 2 received value: Int64Index([1200, 1201, 1202, 1203, 1204, 1205, 1206, 1207, 1208, 1209,
            ...
            1590, 1591, 1592, 1593, 1594, 1595, 1596, 1597, 1598, 1599],
           dtype='int64', length=400)
Int64Index([600, 600, 601, 601, 602, 602, 603, 603, 604, 604,
            ...
            795, 795, 796, 796, 797, 797, 798, 798, 799, 799],
           dtype='int64', length=400)
Task 2 waiting for item...
done sleeping
sleeping
Task 2 received value: Int64Index([1600, 1601, 1602, 1603, 1604, 1605, 1606, 1607, 1608, 1609,
            ...
            1990, 1991, 1992, 1993, 1994, 1995, 1996, 1997, 1998, 1999],
           dtype='int64', length=400)
Int64Index([800, 800, 801, 801, 802, 802, 803, 803, 804, 804,
            ...
            995, 995, 996, 996, 997, 997, 998, 998, 999, 999],
           dtype='int64', length=400)
Task 2 waiting for item...
done sleeping
sleeping
Task 2 received value: Int64Index([2000, 2001, 2002, 2003, 2004, 2005, 2006, 2007, 2008, 2009,
            ...
            2390, 2391, 2392, 2393, 2394, 2395, 2396, 2397, 2398, 2399],
           dtype='int64', length=400)
Int64Index([1000, 1000, 1001, 1001, 1002, 1002, 1003, 1003, 1004, 1004,
            ...
            1195, 1195, 1196, 1196, 1197, 1197, 1198, 1198, 1199, 1199],
           dtype='int64', length=400)
Task 2 waiting for item...
done sleeping
sleeping
Task 2 received value: Int64Index([2400, 2401, 2402, 2403, 2404, 2405, 2406, 2407, 2408, 2409,
            ...
            2790, 2791, 2792, 2793, 2794, 2795, 2796, 2797, 2798, 2799],
           dtype='int64', length=400)
Int64Index([1200, 1200, 1201, 1201, 1202, 1202, 1203, 1203, 1204, 1204,
            ...
            1395, 1395, 1396, 1396, 1397, 1397, 1398, 1398, 1399, 1399],
           dtype='int64', length=400)
Task 2 waiting for item...
done sleeping
sleeping
Task 2 received value: Int64Index([2800, 2801, 2802, 2803, 2804, 2805, 2806, 2807, 2808, 2809,
            ...
            3190, 3191, 3192, 3193, 3194, 3195, 3196, 3197, 3198, 3199],
           dtype='int64', length=400)
Int64Index([1400, 1400, 1401, 1401, 1402, 1402, 1403, 1403, 1404, 1404,
            ...
            1595, 1595, 1596, 1596, 1597, 1597, 1598, 1598, 1599, 1599],
           dtype='int64', length=400)
Task 2 waiting for item...
done sleeping
sleeping
Task 2 received value: Int64Index([3200, 3201, 3202, 3203, 3204, 3205, 3206, 3207, 3208, 3209,
            ...
            3590, 3591, 3592, 3593, 3594, 3595, 3596, 3597, 3598, 3599],
           dtype='int64', length=400)
Int64Index([1600, 1600, 1601, 1601, 1602, 1602, 1603, 1603, 1604, 1604,
            ...
            1795, 1795, 1796, 1796, 1797, 1797, 1798, 1798, 1799, 1799],
           dtype='int64', length=400)
Task 2 waiting for item...
done sleeping
sleeping
Task 2 received value: Int64Index([3600, 3601, 3602, 3603, 3604, 3605, 3606, 3607, 3608, 3609,
            ...
            3990, 3991, 3992, 3993, 3994, 3995, 3996, 3997, 3998, 3999],
           dtype='int64', length=400)
Int64Index([1800, 1800, 1801, 1801, 1802, 1802, 1803, 1803, 1804, 1804,
            ...
            1995, 1995, 1996, 1996, 1997, 1997, 1998, 1998, 1999, 1999],
           dtype='int64', length=400)
Task 2 waiting for item...
done sleeping
sleeping
Task 2 received value: Int64Index([4000, 4001, 4002, 4003, 4004, 4005, 4006, 4007, 4008, 4009,
            ...
            4390, 4391, 4392, 4393, 4394, 4395, 4396, 4397, 4398, 4399],
           dtype='int64', length=400)
Int64Index([2000, 2000, 2001, 2001, 2002, 2002, 2003, 2003, 2004, 2004,
            ...
            2195, 2195, 2196, 2196, 2197, 2197, 2198, 2198, 2199, 2199],
           dtype='int64', length=400)
Task 2 waiting for item...
done sleeping
sleeping
Task 2 received value: Int64Index([4400, 4401, 4402, 4403, 4404, 4405, 4406, 4407, 4408, 4409,
            ...
            4790, 4791, 4792, 4793, 4794, 4795, 4796, 4797, 4798, 4799],
           dtype='int64', length=400)
Int64Index([2200, 2200, 2201, 2201, 2202, 2202, 2203, 2203, 2204, 2204,
            ...
            2395, 2395, 2396, 2396, 2397, 2397, 2398, 2398, 2399, 2399],
           dtype='int64', length=400)
Task 2 waiting for item...
done sleeping
sleeping
Task 2 received value: Int64Index([4800, 4801, 4802, 4803, 4804, 4805, 4806, 4807, 4808, 4809,
            ...
            5190, 5191, 5192, 5193, 5194, 5195, 5196, 5197, 5198, 5199],
           dtype='int64', length=400)
Int64Index([2400, 2400, 2401, 2401, 2402, 2402, 2403, 2403, 2404, 2404,
            ...
            2595, 2595, 2596, 2596, 2597, 2597, 2598, 2598, 2599, 2599],
           dtype='int64', length=400)
Task 2 waiting for item...
done sleeping
sleeping
Task 2 received value: Int64Index([5200, 5201, 5202, 5203, 5204, 5205, 5206, 5207, 5208, 5209,
            ...
            5590, 5591, 5592, 5593, 5594, 5595, 5596, 5597, 5598, 5599],
           dtype='int64', length=400)
Int64Index([2600, 2600, 2601, 2601, 2602, 2602, 2603, 2603, 2604, 2604,
            ...
            2795, 2795, 2796, 2796, 2797, 2797, 2798, 2798, 2799, 2799],
           dtype='int64', length=400)
Task 2 waiting for item...
done sleeping
sleeping
Task 2 received value: Int64Index([5600, 5601, 5602, 5603, 5604, 5605, 5606, 5607, 5608, 5609,
            ...
            5990, 5991, 5992, 5993, 5994, 5995, 5996, 5997, 5998, 5999],
           dtype='int64', length=400)
Int64Index([2800, 2800, 2801, 2801, 2802, 2802, 2803, 2803, 2804, 2804,
            ...
            2995, 2995, 2996, 2996, 2997, 2997, 2998, 2998, 2999, 2999],
           dtype='int64', length=400)
Task 2 waiting for item...
done sleeping
sleeping
Task 2 received value: Int64Index([6000, 6001, 6002, 6003, 6004, 6005, 6006, 6007, 6008, 6009,
            ...
            6390, 6391, 6392, 6393, 6394, 6395, 6396, 6397, 6398, 6399],
           dtype='int64', length=400)
Int64Index([3000, 3000, 3001, 3001, 3002, 3002, 3003, 3003, 3004, 3004,
            ...
            3195, 3195, 3196, 3196, 3197, 3197, 3198, 3198, 3199, 3199],
           dtype='int64', length=400)
Task 2 waiting for item...
done sleeping
sleeping
Task 2 received value: Int64Index([6400, 6401, 6402, 6403, 6404, 6405, 6406, 6407, 6408, 6409,
            ...
            6790, 6791, 6792, 6793, 6794, 6795, 6796, 6797, 6798, 6799],
           dtype='int64', length=400)
Int64Index([3200, 3200, 3201, 3201, 3202, 3202, 3203, 3203, 3204, 3204,
            ...
            3395, 3395, 3396, 3396, 3397, 3397, 3398, 3398, 3399, 3399],
           dtype='int64', length=400)
Task 2 waiting for item...
done sleeping
sleeping
Task 2 received value: Int64Index([6800, 6801, 6802, 6803, 6804, 6805, 6806, 6807, 6808, 6809,
            ...
            7190, 7191, 7192, 7193, 7194, 7195, 7196, 7197, 7198, 7199],
           dtype='int64', length=400)
Int64Index([3400, 3400, 3401, 3401, 3402, 3402, 3403, 3403, 3404, 3404,
            ...
            3595, 3595, 3596, 3596, 3597, 3597, 3598, 3598, 3599, 3599],
           dtype='int64', length=400)
Task 2 waiting for item...
done sleeping
sleeping
Task 2 received value: Int64Index([7200, 7201, 7202, 7203, 7204, 7205, 7206, 7207, 7208, 7209,
            ...
            7590, 7591, 7592, 7593, 7594, 7595, 7596, 7597, 7598, 7599],
           dtype='int64', length=400)
Int64Index([3600, 3600, 3601, 3601, 3602, 3602, 3603, 3603, 3604, 3604,
            ...
            3795, 3795, 3796, 3796, 3797, 3797, 3798, 3798, 3799, 3799],
           dtype='int64', length=400)
Task 2 waiting for item...
done sleeping
sleeping
Task 2 received value: Int64Index([7600, 7601, 7602, 7603, 7604, 7605, 7606, 7607, 7608, 7609,
            ...
            7990, 7991, 7992, 7993, 7994, 7995, 7996, 7997, 7998, 7999],
           dtype='int64', length=400)
Int64Index([3800, 3800, 3801, 3801, 3802, 3802, 3803, 3803, 3804, 3804,
            ...
            3995, 3995, 3996, 3996, 3997, 3997, 3998, 3998, 3999, 3999],
           dtype='int64', length=400)
Task 2 waiting for item...
done sleeping
sleeping
Task 2 received value: Int64Index([8000, 8001, 8002, 8003, 8004, 8005, 8006, 8007, 8008, 8009,
            ...
            8390, 8391, 8392, 8393, 8394, 8395, 8396, 8397, 8398, 8399],
           dtype='int64', length=400)
Int64Index([4000, 4000, 4001, 4001, 4002, 4002, 4003, 4003, 4004, 4004,
            ...
            4195, 4195, 4196, 4196, 4197, 4197, 4198, 4198, 4199, 4199],
           dtype='int64', length=400)
Task 2 waiting for item...
done sleeping
sleeping
Task 2 received value: Int64Index([8400, 8401, 8402, 8403, 8404, 8405, 8406, 8407, 8408, 8409,
            ...
            8790, 8791, 8792, 8793, 8794, 8795, 8796, 8797, 8798, 8799],
           dtype='int64', length=400)
Int64Index([4200, 4200, 4201, 4201, 4202, 4202, 4203, 4203, 4204, 4204,
            ...
            4395, 4395, 4396, 4396, 4397, 4397, 4398, 4398, 4399, 4399],
           dtype='int64', length=400)
Task 2 waiting for item...

CancelledError:

In [ ]:
import asyncio
import queue

async def task1(q):
    print("Task 1 started")
    my_list = [1, 2, 3, 4, 5]
    for i in my_list:
        print(f"putting in {i}")
        await q.put(i)
        print("sleeping")
        await asyncio.sleep(3)
        print("done sleeping")
    print("Task 1 completed")

# async def task2(q):
#     print("Task 2 started")
#     while True:
#         try:
#             value = q.get()
#             print("Task 2 received value:", value)
#         except queue.Empty():
#             print("Task 2 waiting for value...")
#             await asyncio.sleep(1)
#             continue
#         if value is None:
#             print("Task 2 completed")
#             break

async def task2(q):
    print("Task 2 started")
    while True:
        print("Task 2 waiting for item...")
        value = await q.get()
        if value is None:
            print("Task 2 completed")
            break
        print("Task 2 received value:", value)


async def main():
    q = asyncio.Queue()
    # Run both tasks concurrently
    task1_coro = asyncio.create_task(task1(q))
    task2_coro = asyncio.create_task(task2(q))

    # Wait for task1 to complete
    await task1_coro

    # Signal task2 to complete
    await q.put(None)
    await task2_coro

# Start the event loop and run the main coroutine
await main()

Task 1 started
putting in 1
sleeping
Task 2 started
Task 2 waiting for item...
Task 2 received value: 1
Task 2 waiting for item...
done sleeping
putting in 2
sleeping
Task 2 received value: 2
Task 2 waiting for item...
done sleeping
putting in 3
sleeping
Task 2 received value: 3
Task 2 waiting for item...
done sleeping
putting in 4
sleeping
Task 2 received value: 4
Task 2 waiting for item...
done sleeping
putting in 5
sleeping
Task 2 received value: 5
Task 2 waiting for item...
done sleeping
Task 1 completed
Task 2 completed

In [84]:
import requests
import json
url = "https://api.repliers.io/listings/C6053387"
headers = {
"repliers-api-key": os.environ['REPLIERS_KEY'],
"Content-Type": "application/json"
}
payload = {}
response = requests.request("GET",url, headers=headers, params=payload)

data = response.json()

df = pd.DataFrame.from_dict(data, orient = 'index')
df = df.transpose()

In [59]:
df.columns

Index(['listDate', 'rooms', 'originalPrice', 'soldDate', 'occupancy',
       'timestamps', 'condominium', 'taxes', 'office', 'type', 'nearby', 'lot',
       'mlsNumber', 'openHouse', 'permissions', 'soldPrice', 'details',
       'class', 'map', 'images', 'address', 'comparables', 'resource', 'raw',
       'updatedOn', 'history', 'daysOnMarket', 'agents', 'coopCompensation',
       'listPrice', 'lastStatus', 'status', 'boardId'],
      dtype='object')

In [85]:
def dfExtractFeatures(df: pd.DataFrame, key: str, columns: list):
    if type(df[key].values[0]) == str:
        try:
            serie = df[key].apply(lambda x: ast.literal_eval(str(x)))
            d = pd.DataFrame.from_dict(serie.tolist())
        except:
            print("String does not match proper conversion methods")
    elif type(df[key].values[0]) == dict:
        serie = pd.Series.to_dict(df[key])
        d = pd.DataFrame.from_dict(serie, orient='index')
    for i in range(len(columns)):
        df[columns[i]] = d[columns[i]]

    return df

In [86]:
address = ['area', 'city', 'district', 'neighborhood']
details = ['numBathrooms','numBedrooms','sqft','style',]
map_ = ['latitude', 'longitude']

df = dfExtractFeatures(df, key = 'address', columns = address)
df = dfExtractFeatures(df, key = 'details', columns = details)
df = dfExtractFeatures(df, key = 'map', columns = map_)

In [87]:
df.columns

Index(['listDate', 'rooms', 'originalPrice', 'soldDate', 'occupancy',
       'timestamps', 'condominium', 'taxes', 'office', 'type', 'nearby', 'lot',
       'mlsNumber', 'openHouse', 'permissions', 'soldPrice', 'details',
       'class', 'map', 'images', 'address', 'comparables', 'resource', 'raw',
       'updatedOn', 'history', 'daysOnMarket', 'agents', 'coopCompensation',
       'listPrice', 'lastStatus', 'status', 'boardId', 'area', 'city',
       'district', 'neighborhood', 'numBathrooms', 'numBedrooms', 'sqft',
       'style', 'latitude', 'longitude'],
      dtype='object')

In [109]:
df['listDate'].values[0]

listDate = dt.datetime.strptime(df['listDate'].values[0].split("T")[0], '%Y-%m-%d')

In [89]:
import datetime as dt

In [90]:
def grab_average_area(df):
    url = f"https://api.repliers.io/listings?resultsPerPage=1000"
    payload = {'area': df['area'].values[0], 'type': df['type'].values[0], 'status': 'A'}
    headers = {'repliers-api-key': os.environ['REPLIERS_KEY']}
    r = requests.request("GET",url, params=payload, headers=headers)
    data = r.json()
    df_area = pd.DataFrame(data['listings'])
    columns = [col for col in df_area.columns if col != 'listPrice']
    df_area = df_area.drop(columns, axis = 1)
    df['listPrice_by_area'] = np.mean(df_area['listPrice'].astype("float").values)


def grab_average_city(df):
    url = f"https://api.repliers.io/listings?resultsPerPage=1000"
    payload = {'city': df['city'].values[0], 'type': df['type'].values[0], 'status': 'A'}
    headers = {'repliers-api-key': os.environ['REPLIERS_KEY']}
    r = requests.request("GET",url, params=payload, headers=headers)
    data = r.json()
    df_city = pd.DataFrame(data['listings'])
    columns = [col for col in df_city.columns if col != 'listPrice']
    df_city = df_city.drop(columns, axis = 1)
    df['listPrice_by_city'] = np.mean(df_city['listPrice'].astype("float").values)

In [91]:
import pickle
sale_file = pickle.load(open(os.getcwd()+"\\models\\sale_model_parameters.sav", 'rb'))
lease_file = pickle.load(open(os.getcwd()+"\\models\\lease_model_parameters.sav", 'rb'))

sale_model = sale_file['model']
sale_columns = sale_file['columns']
sale_feat_index = sale_file['idx']

In [94]:
def feature_engineer_single_listing(df, model_columns, model_idx):
    #Replace any empty strings or nan values that are not specific to the pandas DataFrame
    df.replace({"": np.nan}, inplace = True)
    df.replace({float("nan"): np.nan}, inplace = True)

    df['listPrice'] = df['listPrice'].astype("float")
    df['soldPrice'] = df['soldPrice'].astype("float")
    
    #Replace any empty strings or nan values that are not specific to the pandas DataFrame
    df.replace({"": np.nan}, inplace = True)
    df.replace({float("nan"): np.nan}, inplace = True)
    
    #Encode map coordinates as floats
    df['latitude'] = df['latitude'].astype("float")
    df['longitude'] = df['longitude'].astype("float")

    #dom
    today = dt.datetime.now()
    if 'listDate' in df.columns:
        try:
            listDate = dt.datetime.strptime(df['listDate'].values[0].split("T")[0], '%Y-%m-%d')
            dom = (today-listDate).day
        except:
            dom = np.nan
    else:
        dom = np.nan 

    df['DOM'] = dom

    #bed bath ratio
    try:
        bedtobath = df['numBathrooms'].astype('float')/df['numBedrooms'].astype('float')
    except:
        bedtobath = np.nan
    
    df['bathtobed_ratio'] = bedtobath

    #sqft and price per sqft
    if '-' in df['sqft']:
        average_sqft = (int(df['sqft'].split("-")[0])+int(df['sqft'].split("-")[1]))/2
        df['avg_sqft'] = average_sqft

        pp_sqft = df['listPrice']/average_sqft
        df['ppsqft'] = pp_sqft
    else:
        avg_sqft = np.nan
        pp_sqft = np.nan

        df['avg_sqft'] = avg_sqft
        df['ppsqft'] = pp_sqft


    #average listing of city
    grab_average_city(df)

    #average listing of area
    grab_average_area(df)

    columns_to_keep = ['originalPrice', 'soldPrice', 'class', 'listPrice', 'area', 'city', 'district', 'neighborhood', 'numBathrooms', 'numBedrooms', 'sqft', 'style', 'latitude', 'longitude', 'DOM', 'avg_sqft', 'ppsqft', 'bathtobed_ratio', 'listPrice_by_area', 'listPrice_by_city']
    columns_to_drop = [col for col in df.columns if col not in columns_to_keep]
    df_agg = df.drop(columns = columns_to_drop, axis = 1)

    df_agg_cats = pd.get_dummies(df_agg)

    df_model_columns = pd.DataFrame(df_agg_cats, columns = model_columns)

    df_listing = pd.DataFrame(df_model_columns, columns = df_model_columns.columns[model_idx])

    return df_listing

In [98]:
df_ = feature_engineer_single_listing(df)

In [99]:
df_

,soldPrice,listPrice,sqft,latitude,longitude,DOM,bathtobed_ratio,avg_sqft,ppsqft,listPrice_by_city,listPrice_by_area,originalPrice_1999000.00,class_ResidentialProperty,area_Toronto,city_Toronto,district_Toronto C04,neighborhood_Bedford Park-Nortown,numBathrooms_2,numBedrooms_2,style_Bungalow
0,0.0,1999000.0,NaN,43.729052,-79.426974,NaN,1.0,NaN,NaN,1424204.466,1424204.466,1,1,1,1,1,1,1,1,1

In [100]:
df_ = pd.DataFrame(df_, columns = sale_columns)

In [101]:
df_

,listPrice,latitude,longitude,DOM,avg_sqft,ppsqft,bathtobed_ratio,listPrice_by_area,listPrice_by_city,originalPrice_100,originalPrice_100000000,originalPrice_101888800,originalPrice_101900000,originalPrice_102400000,originalPrice_102500000,originalPrice_102800000,originalPrice_102880000,originalPrice_102990000,originalPrice_103500000,originalPrice_103800000,originalPrice_103900000,originalPrice_103990000,originalPrice_104900000,originalPrice_104980000,originalPrice_104990000,originalPrice_104999900,originalPrice_105000000,originalPrice_105700000,originalPrice_105888800,originalPrice_106900000,originalPrice_106990000,originalPrice_107490000,originalPrice_107500000,originalPrice_107700000,originalPrice_108000000,originalPrice_108500000,originalPrice_108800000,originalPrice_108880000,originalPrice_108888800,originalPrice_108900000,originalPrice_109000000,originalPrice_109500000,originalPrice_109800000,originalPrice_109880000,originalPrice_109890000,originalPrice_109900000,originalPrice_109970000,originalPrice_109980000,originalPrice_109990000,originalPrice_109999000,originalPrice_109999900,originalPrice_110000000,originalPrice_110090000,originalPrice_112490000,originalPrice_112500000,originalPrice_112900000,originalPrice_112990000,originalPrice_113000000,originalPrice_114800000,originalPrice_114900000,originalPrice_114990000,originalPrice_114999900,originalPrice_115000000,originalPrice_115400000,originalPrice_115490000,originalPrice_115700000,originalPrice_115990000,originalPrice_116000000,originalPrice_116500000,originalPrice_116888800,originalPrice_116900000,originalPrice_116990000,originalPrice_117500000,originalPrice_117900000,originalPrice_118000000,originalPrice_118800000,originalPrice_118880000,originalPrice_118888800,originalPrice_118900000,originalPrice_119000000,originalPrice_119500000,originalPrice_119700000,originalPrice_119800000,originalPrice_119900000,originalPrice_119978600,originalPrice_119980000,originalPrice_119988800,originalPrice_119990000,originalPrice_119999000,originalPrice_119999900,originalPrice_120000000,originalPrice_122500000,originalPrice_122550000,originalPrice_122800000,originalPrice_123990000,originalPrice_124500000,originalPrice_124800000,originalPrice_124880000,originalPrice_124900000,originalPrice_124980000,originalPrice_124990000,originalPrice_124999000,originalPrice_125000000,originalPrice_125888800,originalPrice_125900000,originalPrice_126900000,originalPrice_127000000,originalPrice_127500000,originalPrice_127888500,originalPrice_127900000,originalPrice_127900100,originalPrice_127990000,originalPrice_127999900,originalPrice_128000000,originalPrice_128800000,originalPrice_128880000,originalPrice_128888800,originalPrice_128900000,originalPrice_128990000,originalPrice_129000000,originalPrice_129500000,originalPrice_129800000,originalPrice_129880000,originalPrice_12990000,originalPrice_129900000,originalPrice_129980000,originalPrice_129990000,originalPrice_129999900,originalPrice_130000000,originalPrice_131900000,originalPrice_132500000,originalPrice_132590000,originalPrice_132900000,originalPrice_132990000,originalPrice_133000000,originalPrice_133388800,originalPrice_133888800,originalPrice_133900000,originalPrice_134900000,originalPrice_134950000,originalPrice_134990000,originalPrice_134999900,originalPrice_135000000,originalPrice_135900000,originalPrice_136800000,originalPrice_136900000,originalPrice_136999900,originalPrice_137488800,originalPrice_137500000,originalPrice_137800000,originalPrice_137900000,originalPrice_137990000,originalPrice_138000000,originalPrice_138080000,originalPrice_138780000,originalPrice_138800000,originalPrice_138880000,originalPrice_138888800,originalPrice_138980000,originalPrice_13900000,originalPrice_139000000,originalPrice_139500000,originalPrice_139880000,originalPrice_139900000,originalPrice_139990000,originalPrice_139999900,originalPrice_140000000,originalPrice_141800000,originalPrice_142500000,originalPrice_142900000,originalPrice_143900000,originalPrice_144800000,originalPrice_144880000,originalPrice_144900000,originalPrice_144990000,originalPrice_144999000,originalPrice_144999900,originalPrice_145000000,originalPrice_146800000,originalPrice_147500000,originalPrice_147900000,originalPrice_147990000,originalPrice_148000000,originalPrice_148400000,originalPrice_148800000,originalPrice_148880000,originalPrice_148888800,originalPrice_148900000,originalPrice_148988800,originalPrice_149000000,originalPrice_149500000,originalPrice_149800000,originalPrice_149880000,originalPrice_149888800,originalPrice_149900000,originalPrice_149988800,originalPrice_149990000,originalPrice_149999900,originalPrice_150000000,originalPrice_152500000,originalPrice_153500000,originalPrice_153880000,originalPrice_153900000,originalPrice_154900000,originalPrice_154990000,originalPrice_154999900,originalPrice_155000000,originalPrice_156500000,originalPrice_156990000,originalPrice_157500000,originalPrice_157900000,originalPrice_157980000,originalPrice_158000000,originalPrice_158800000,originalPrice_158900000,originalPrice_159500000,originalPrice_159590000,originalPrice_159900000,originalPrice_159990000,originalPrice_159999000,originalPrice_159999900,originalPrice_160000000,originalPrice_162000000,originalPrice_162490000,originalPrice_162500000,originalPrice_163900000,originalPrice_164900000,originalPrice_164980000,originalPrice_164990000,originalPrice_165000000,originalPrice_165800000,originalPrice_165888800,originalPrice_165900000,originalPrice_167490000,originalPrice_167900000,originalPrice_167990000,originalPrice_168500000,originalPrice_168800000,originalPrice_168888800,originalPrice_16900000,originalPrice_169000000,originalPrice_169500000,originalPrice_169800000,originalPrice_169880000,originalPrice_169899000,originalPrice_169900000,originalPrice_169980000,originalPrice_169990000,originalPrice_172000000,originalPrice_172098100,originalPrice_172500000,originalPrice_173900000,originalPrice_174900000,originalPrice_175000000,originalPrice_176990000,originalPrice_177500000,originalPrice_177900000,originalPrice_178800000,originalPrice_178880000,originalPrice_179000000,originalPrice_179500000,originalPrice_179800000,originalPrice_179900000,originalPrice_179980000,originalPrice_179999900,originalPrice_180000000,originalPrice_181800000,originalPrice_184900000,originalPrice_185000000,originalPrice_186900000,originalPrice_187900000,originalPrice_188800000,originalPrice_189800000,originalPrice_189900000,originalPrice_189980000,originalPrice_189990000,originalPrice_190000000,originalPrice_194500000,originalPrice_194900000,originalPrice_194999000,originalPrice_195000000,originalPrice_197400000,originalPrice_198000000,originalPrice_198800000,originalPrice_198880000,originalPrice_198900000,originalPrice_199000000,originalPrice_199500000,originalPrice_199800000,originalPrice_199850000,originalPrice_199880000,originalPrice_199900000,originalPrice_199950000,originalPrice_199980000,originalPrice_199988800,originalPrice_199999900,originalPrice_200000000,originalPrice_205000000,originalPrice_208800000,originalPrice_209000000,originalPrice_209900000,originalPrice_209988800,originalPrice_209990000,originalPrice_210000000,originalPrice_213990000,originalPrice_214900000,originalPrice_218000000,originalPrice_218888800,originalPrice_219800000,originalPrice_219900000,originalPrice_219990000,originalPrice_219999900,originalPrice_220000000,originalPrice_224900000,originalPrice_22500000,originalPrice_225000000,originalPrice_228800000,originalPrice_22990000,originalPrice_229900000,originalPrice_230000000,originalPrice_235000000,originalPrice_236800000,originalPrice_237999900,originalPrice_238000000,originalPrice_238800000,originalPrice_239500000,originalPrice_239900000,originalPrice_239999900,originalPrice_240000000,originalPrice_242500000,originalPrice_24500000,originalPrice_245000000,originalPrice_246400000,originalPrice_246990000,originalPrice_248688800,originalPrice_248800000,originalPrice_249000000,originalPrice_249500000,originalPrice_249800000,originalPrice_24990000,originalPrice_249900000,originalPrice_249990000,originalPrice_250000000,originalPrice_255000000,originalPrice_256880000,originalPrice_259500000,originalPrice_259800000,originalPrice_259900000,originalPrice_25999900,originalPrice_265000000,originalPrice_268600000,originalPrice_268880000,originalPrice_268888800,originalPrice_269500000,originalPrice_269800000,originalPrice_269900000,originalPrice_269998800,originalPrice_269999900,originalPrice_270000000,originalPrice_278900000,originalPrice_279500000,originalPrice_279900000,originalPrice_279999000,originalPrice_280000000,originalPrice_285000000,originalPrice_288000000,originalPrice_288800000,originalPrice_28900000,originalPrice_289500000,originalPrice_289800000,originalPrice_28990000,originalPrice_29500000,originalPrice_298000000,originalPrice_298888800,originalPrice_29900000,originalPrice_299000000,originalPrice_299500000,originalPrice_299800000,originalPrice_299880000,originalPrice_29990000,originalPrice_299900000,originalPrice_299988800,originalPrice_299990000,originalPrice_308800000,originalPrice_309500000,originalPrice_309900000,originalPrice_319500000,originalPrice_319999900,originalPrice_320000000,originalPrice_32500000,originalPrice_327900000,originalPrice_329500000,originalPrice_329900000,originalPrice_33000000,originalPrice_33500000,originalPrice_335000000,originalPrice_33550000,originalPrice_338888800,originalPrice_339500000,originalPrice_348880000,originalPrice_34888800,originalPrice_34890000,originalPrice_34900000,originalPrice_349000000,originalPrice_349500000,originalPrice_34990000,originalPrice_35000000,originalPrice_350000000,originalPrice_35750000,originalPrice_35990000,originalPrice_35999700,originalPrice_36500000,originalPrice_365000000,originalPrice_369000000,originalPrice_36990000,originalPrice_369900000,originalPrice_37490000,originalPrice_375000000,originalPrice_378850000,originalPrice_37900000,originalPrice_379500000,originalPrice_37980000,originalPrice_379800000,originalPrice_37990000,originalPrice_38900000,originalPrice_38990000,originalPrice_39490000,originalPrice_39800000,originalPrice_398800000,originalPrice_39900000,originalPrice_39909000,originalPrice_39988800,originalPrice_39990000,originalPrice_399900000,originalPrice_39999900,originalPrice_40000000,originalPrice_40500000,originalPrice_408800000,originalPrice_41500000,originalPrice_41900000,originalPrice_419500000,originalPrice_419888800,originalPrice_41990000,originalPrice_42500000,originalPrice_425000000,originalPrice_42900000,originalPrice_42990000,originalPrice_43000000,originalPrice_43490000,originalPrice_43900000,originalPrice_43990000,originalPrice_44000000,originalPrice_44900000,originalPrice_44990000,originalPrice_45000000,originalPrice_45500000,originalPrice_45900000,originalPrice_45990000,originalPrice_46000000,originalPrice_46500000,originalPrice_46800000,originalPrice_46990000,originalPrice_47400000,originalPrice_47499500,originalPrice_47500000,originalPrice_47700000,originalPrice_47888000,originalPrice_47990000,originalPrice_47999900,originalPrice_48490000,originalPrice_48500000,originalPrice_48590000,originalPrice_48800000,originalPrice_488000000,originalPrice_48900000,originalPrice_489500000,originalPrice_48980000,originalPrice_48990000,originalPrice_48999900,originalPrice_49000000,originalPrice_49500000,originalPrice_495000000,originalPrice_49800000,originalPrice_498000000,originalPrice_49880000,originalPrice_49888800,originalPrice_49890000,originalPrice_49900000,originalPrice_49964900,originalPrice_49988800,originalPrice_49990000,originalPrice_49999900,originalPrice_50000000,originalPrice_50900000,originalPrice_50990000,originalPrice_51490000,originalPrice_51500000,originalPrice_51800000,originalPrice_51888800,...,neighborhood_CrescentTown,neighborhood_CrestwoodSpringfarmYorkhill,neighborhood_Crosby,neighborhood_CrownPoint,neighborhood_CundlesEast,neighborhood_Danforth,neighborhood_DanforthVillageEastYork,neighborhood_Dempsey,neighborhood_Devonsleigh,neighborhood_Dixie,neighborhood_DonValleyVillage,neighborhood_Donevan,neighborhood_DorsetPark,neighborhood_DovercourtWallaceEmersonJunction,neighborhood_DownsviewRodingCFB,neighborhood_Downtown,neighborhood_DowntownBrampton,neighborhood_DufferinGrove,neighborhood_DuffinHeights,neighborhood_Dundalk,neighborhood_Dundas,neighborhood_Dunnville,neighborhood_Durand,neighborhood_EastBayfield,neighborhood_EastCredit,neighborhood_EastEndDanforth,neighborhood_EastWoodbridge,neighborhood_EastYork,neighborhood_Eastdale,neighborhood_Eastlake,neighborhood_Eastmount,neighborhood_EdenbridgeHumberValley,neighborhood_EdgehillDrive,neighborhood_EglintonEast,neighborhood_Elmvale,neighborhood_EloraSalem,neighborhood_EnglemountLawrence,neighborhood_Erin,neighborhood_ErinMills,neighborhood_Erindale,neighborhood_EringateCentennialWestDeane,neighborhood_EtobicokeWestMall,neighborhood_Everett,neighborhood_Fairview,neighborhood_Falkirk,neighborhood_Farewell,neighborhood_FenelonFalls,neighborhood_Fergus,neighborhood_Fessenden,neighborhood_FlemingdonPark,neighborhood_FletchersCreekSouth,neighborhood_FletchersCreekVillage,neighborhood_FletchersMeadow,neighborhood_FletchersWest,neighborhood_Ford,neighborhood_ForestHillNorth,neighborhood_Freeman,neighborhood_Fruitland,neighborhood_Georgetown,neighborhood_GeorgianDrive,neighborhood_Gibson,neighborhood_Gilford,neighborhood_GlenAbbey,neighborhood_GlenShields,neighborhood_GlenWilliams,neighborhood_GlenfieldJaneHeights,neighborhood_Glenview,neighborhood_GlenwayEstates,neighborhood_GoreIndustrialNorth,neighborhood_GorewayDriveCorridor,neighborhood_GorhamCollegeManor,neighborhood_GrandValley,neighborhood_Grandview,neighborhood_GrangeHillEast,neighborhood_Greensborough,neighborhood_GreenwoodCoxwell,neighborhood_GroveEast,neighborhood_Guildwood,neighborhood_Haldimand,neighborhood_HanlonCreek,neighborhood_Hanover,neighborhood_Harding,neighborhood_Harrison,neighborhood_Hastings,neighborhood_Havelock,neighborhood_Hawkestone,neighborhood_Headon,neighborhood_HeartLake,neighborhood_HeartLakeEast,neighborhood_HeartLakeWest,neighborhood_HenryFarm,neighborhood_HiawathaFirstNation,neighborhood_HighParkNorth,neighborhood_HighParkSwansea,neighborhood_Highbush,neighborhood_HillPark,neighborhood_HillcrestVillage,neighborhood_Hillier,neighborhood_Hillsburgh,neighborhood_HistoricLakeshoreCommunities,neighborhood_HollandLanding,neighborhood_Holly,neighborhood_Homeside,neighborhood_HumberHeights,neighborhood_HumberSummit,neighborhood_HumberleaPelmoParkW5,neighborhood_Humbermede,neighborhood_HumewoodCedarvale,neighborhood_Huntington,neighborhood_HuronHeightsLeslieValley,neighborhood_Hurontario,neighborhood_InnisShore,neighborhood_Ionview,neighborhood_IroquoisRidgeNorth,neighborhood_IroquoisRidgeSouth,neighborhood_IslingtonWoods,neighborhood_IslingtonCityCentreWest,neighborhood_Jefferson,neighborhood_Jerome,neighborhood_JunctionArea,neighborhood_KeelesdaleEglintonWest,neighborhood_KennedyPark,neighborhood_KensingtonChinatown,neighborhood_KeswickNorth,neighborhood_KeswickSouth,neighborhood_KingCity,neighborhood_KingsviewVillageTheWestway,neighborhood_KingswaySouth,neighborhood_Kirkendall,neighborhood_Kirkfield,neighborhood_Kleinburg,neighborhood_KortrightHills,neighborhood_LAmoreaux,neighborhood_LaSalle,neighborhood_Lakefield,neighborhood_Lakeshore,neighborhood_Lakeview,neighborhood_LambtonBabyPoint,neighborhood_Landsdale,neighborhood_Langstaff,neighborhood_LansingWestgate,neighborhood_Lawfield,neighborhood_LawrenceParkNorth,neighborhood_LawrenceParkSouth,neighborhood_Leaside,neighborhood_LetitiaHeights,neighborhood_Lindsay,neighborhood_Lisgar,neighborhood_LittleBritain,neighborhood_LittleLake,neighborhood_LittlePortugal,neighborhood_Liverpool,neighborhood_LongBranch,neighborhood_Loretto,neighborhood_LornePark,neighborhood_LyndeCreek,neighborhood_Madoc,neighborhood_Malton,neighborhood_Malvern,neighborhood_Maple,neighborhood_MapleLeaf,neighborhood_MarkhamVillage,neighborhood_MarklandWood,neighborhood_Markville,neighborhood_McLaughlin,neighborhood_Meadowlands,neighborhood_Meadowvale,neighborhood_MeadowvaleVillage,neighborhood_Meaford,neighborhood_Midhurst,neighborhood_Midland,neighborhood_MillPond,neighborhood_MillikenMillsEast,neighborhood_MillikenMillsWest,neighborhood_Mimico,neighborhood_Mineola,neighborhood_MississaugaValleys,neighborhood_Monaghan,neighborhood_Morningside,neighborhood_Morriston,neighborhood_MossPark,neighborhood_MountForest,neighborhood_MountHope,neighborhood_MountOliveSilverstoneJamestown,neighborhood_MountPleasantEast,neighborhood_MountPleasantWest,neighborhood_MtAlbert,neighborhood_NewLowell,neighborhood_NewToronto,neighborhood_Newcastle,neighborhood_NewtonbrookEast,neighborhood_NewtonbrookWest,neighborhood_Niagara,neighborhood_Nobleton,neighborhood_Norfolk,neighborhood_Normanhurst,neighborhood_NorthMarysburgh,neighborhood_NorthRichvale,neighborhood_NorthRiverdale,neighborhood_NorthStJamesTown,neighborhood_Northcrest,neighborhood_NortheastAjax,neighborhood_Northgate,neighborhood_Northglen,neighborhood_Northwest,neighborhood_NorthwestAjax,neighborhood_NorthwestBrampton,neighborhood_NorthwoodPark,neighborhood_Norwood,neighborhood_Nottawa,neighborhood_OConnorParkview,neighborhood_ONeill,neighborhood_OakRidges,neighborhood_OakRidgesLakeWilcox,neighborhood_Oakridge,neighborhood_OakwoodVillage,neighborhood_Observatory,neighborhood_OldMarkhamVillage,neighborhood_OldMilton,neighborhood_OldOakville,neighborhood_OldUniversity,neighborhood_Orangeville,neighborhood_Orchard,neighborhood_Orillia,neighborhood_Orono,neighborhood_Otonabee,neighborhood_Ottawa,neighborhood_PainswickNorth,neighborhood_PainswickSouth,neighborhood_Palgrave,neighborhood_Palmer,neighborhood_PalmerstonLittleItaly,neighborhood_Paris,neighborhood_Parkview,neighborhood_ParkwoodGardens,neighborhood_ParkwoodsDonalda,neighborhood_Patterson,neighborhood_Pefferlaw,neighborhood_Penetanguishene,neighborhood_Perkinsfield,neighborhood_PineRidge,neighborhood_Pinecrest,neighborhood_PleasantView,neighborhood_Pontypool,neighborhood_PortCredit,neighborhood_PortHope,neighborhood_PortPerry,neighborhood_PortWhitby,neighborhood_Pottageville,neighborhood_PrincessRosethorn,neighborhood_PringleCreek,neighborhood_QueenStreetCorridor,neighborhood_Queensville,neighborhood_Raleigh,neighborhood_Rathwood,neighborhood_Raymerville,neighborhood_RegentPark,neighborhood_RiverOaks,neighborhood_Riverdale,neighborhood_RockcliffeSmythe,neighborhood_Rockwood,neighborhood_RollingAcres,neighborhood_Rolston,neighborhood_Roncesvalles,neighborhood_Rose,neighborhood_Rosebank,neighborhood_Rosedale,neighborhood_RosedaleMoorePark,neighborhood_Roseland,neighborhood_Rosemont,neighborhood_RougeE10,neighborhood_RougeE11,neighborhood_RougeFairways,neighborhood_RougePark,neighborhood_Rougemount,neighborhood_RoyalOrchard,neighborhood_RunnymedeBloorWestVillage,neighborhood_RuralAdjalaTosorontio,neighborhood_RuralAlnwickHaldimand,neighborhood_RuralAmaranth,neighborhood_RuralAsphodelNorwood,neighborhood_RuralAurora,neighborhood_RuralBarrieSoutheast,neighborhood_RuralBarrieSouthwest,neighborhood_RuralBlueMountains,neighborhood_RuralBradfordWestGwillimbury,neighborhood_RuralBrighton,neighborhood_RuralCaledon,neighborhood_RuralCavanMonaghan,neighborhood_RuralClearview,neighborhood_RuralCramahe,neighborhood_RuralDouroDummer,neighborhood_RuralEastGwillimbury,neighborhood_RuralEastLutherGrandValley,neighborhood_RuralEldon,neighborhood_RuralErin,neighborhood_RuralEssa,neighborhood_RuralFenelon,neighborhood_RuralFlamborough,neighborhood_RuralGeorgianBluffs,neighborhood_RuralGlanbrook,neighborhood_RuralGuelphEramosa,neighborhood_RuralHaltonHills,neighborhood_RuralHamilton,neighborhood_RuralHavelockBelmontMethuen,neighborhood_RuralInnisfil,neighborhood_RuralKing,neighborhood_RuralMeaford,neighborhood_RuralMono,neighborhood_RuralMulmur,neighborhood_RuralNewTecumseth,neighborhood_RuralNorthKawartha,neighborhood_RuralOakville,neighborhood_RuralOroMedonte,neighborhood_RuralOtonabeeSouthMonaghan,neighborhood_RuralPickering,neighborhood_RuralPortH

In [102]:
df_listing = pd.DataFrame(df_, columns= df_.columns[sale_feat_index])

In [103]:
df_listing

,listPrice,latitude,longitude,DOM,avg_sqft,ppsqft,bathtobed_ratio,listPrice_by_area,listPrice_by_city,originalPrice_99900000,class_CondoProperty,city_Kitchener,city_Markham,city_RichmondHill,numBathrooms_1,numBathrooms_2,numBathrooms_3,numBathrooms_4,numBathrooms_5,numBedrooms_2,numBedrooms_3,numBedrooms_4,numBedrooms_5,style_2Storey,style_Bungalow
0,1999000.0,43.729052,-79.426974,NaN,NaN,NaN,1.0,1424204.466,1424204.466,NaN,NaN,NaN,NaN,NaN,NaN,1,NaN,NaN,NaN,1,NaN,NaN,NaN,NaN,1

In [130]:
x = pd.DataFrame(columns = ['a', 'a', 'b'])

In [131]:
# asdf = asdf.drop(['a'], axis = 1)
print(set(x.columns))
x.columns

list(x.columns).count('a')

list(x.columns) != set(x.columns)

t = set([y for y in x if list(x.columns).count(y) > 1])

asdf = x.drop(t, axis = 1)

asdf

{'a', 'b'}

Empty DataFrame
Columns: [b]
Index: []

In [137]:
import sklearn
import flask 
import flask_cors
import lightgbm
print(pd.__version__)
print(np.__version__)
print(sklearn.__version__)
print(flask.__version__)
print(flask_cors.__version__)
print(lightgbm.__version__)

1.4.4
1.21.5
1.0.2
2.3.2
3.0.10
3.3.5